contrib/net/http: add method RTWithSpanOptions
DataDog/dd-trace-go pull request #1005
Opened 2021-09-10 15:12 UTC by afarbos

Allowing to provide additional options
when starting a new span with the round tripper.

Related issue: https://github.com/DataDog/dd-trace-go/issues/984

2021-09-16 06:01 UTC, knusbaum commented on contrib/net/http/roundtripper_test.go
> +	)
Let's just use the `:=` syntax instead of the `const` and `var` blocks.

2021-09-16 06:02 UTC, knusbaum requested changes
I just have a style comment.

2021-09-16 06:02 UTC, knusbaum commented on contrib/net/http/roundtripper_test.go
> +	)
Let's just use the `:=` syntax instead of the `const` and `var` blocks.

2021-11-08 22:55 UTC, afarbos commented
> @afarbos any interest to continue this? It's been a month.

Sorry for some reason I did not receive the notification.

2021-11-11 22:11 UTC, knusbaum approved these changes
LGTM, Thanks.

2021-11-11 22:34 UTC, merged