Return correct wrapped response writer writer
DataDog/dd-trace-go pull request #1078
Opened 2021-12-03 20:34 UTC by renanrt

We **should** return the wrapped response writer and **NOT** the original one.

In response to [this](https://github.com/DataDog/dd-trace-go/issues/1076) issue.

2021-12-04 00:53 UTC, knusbaum requested changes
One nit about import order for the linter.

2021-12-04 00:53 UTC, knusbaum commented on contrib/internal/httputil/trace_gen.go
> +	"net/http"
This change should be reverted, but everything else looks alright.

2021-12-06 09:48 UTC, Julio-Guerra requested changes
Thanks for contributing :-)

I just added the test that was missing and would have caught the issue you fix here.

The patch you propose is actually incorrect: `trace_gen.go` is a generated file and you should instead fix `make_responsewriter.go` and then run `go run ./make_responsewriter.go > trace_gen.go` to fix `trace_gen.go`.

Thank you :-)

2021-12-06 09:49 UTC, Julio-Guerra commented on contrib/internal/httputil/trace_gen.go
> +		}{mw}
The following is enough:
```suggestion
		w = mw
```

2021-12-06 11:21 UTC, gbbr requested changes

2021-12-06 11:21 UTC, gbbr commented on contrib/internal/httputil/trace_gen.go
> +	default:
This is generated code. If you want changes, you have to modify the code that generates this file. 

https://github.com/DataDog/dd-trace-go/blob/a71ee32b5e69efa07207a5959df796f157ba410c/contrib/internal/httputil/trace_gen.go#L6

2021-12-14 13:02 UTC, renanrt commented
Updated the file that generates the code, tested and it seems to be working fine!

2021-12-14 16:24 UTC, Julio-Guerra approved these changes

2021-12-16 10:55 UTC, merged