internal/appsec/config.go: fix waf timeout configuration
DataDog/dd-trace-go pull request #1129
Opened 2022-01-17 21:53 UTC by Julio-Guerra

Along with exhaustive config testing to avoid such problems.

2022-01-17 22:29 UTC, Julio-Guerra commented on internal/appsec/config.go
> +		if err == nil {
the reason why configuring the waf timeout was broken: this condition was wrong ^^'

2022-01-18 09:29 UTC, Hellzy approved these changes

2022-01-18 09:33 UTC, Hellzy requested changes

2022-01-18 09:33 UTC, Hellzy commented on internal/appsec/config_test.go
> +			require.NoError(t, os.Setenv(wafTimeoutEnvVar, "not a duration string"))
```suggestion
			require.NoError(t, os.Setenv(wafTimeoutEnvVar, "-1s"))
```

2022-01-18 09:33 UTC, Hellzy commented on internal/appsec/config_test.go
> +			require.NoError(t, os.Setenv(wafTimeoutEnvVar, "not a duration string"))
Copy/Paste oversight?

2022-01-18 09:40 UTC, Hellzy submitted a review, later dismissed

2022-01-18 10:19 UTC, Hellzy approved these changes

2022-01-18 10:20 UTC, merged