Disables Datadog internal tag propagation
DataDog/dd-trace-go pull request #1182
Opened 2022-02-24 23:06 UTC by Barbayar

2022-02-24 23:14 UTC, brettlangdon reviewed
lgtm

2022-02-24 23:14 UTC, brettlangdon commented on ddtrace/tracer/tracer_test.go
> +	horizontalPropagation = true
can we add an assertion that we do not inject tags by default?

2022-02-25 00:06 UTC, knusbaum requested changes
Can we just delete this code? 
We can always bring it back when we know what the fix will be. Right now we don't know what the solution will be or when it will happen.

2022-02-25 15:36 UTC, knusbaum approved these changes

2022-02-25 16:57 UTC, merged