contrib/net/http: make roundTripper propagation (inject, extract) optional
DataDog/dd-trace-go pull request #1224
Opened 2022-03-29 12:30 UTC by rangelrealecb

I need to make an http call to a vendor, and I would like to trace this call (and its parameters), but using the current roundTripper would "leak" the trace_id / parent_id as headers, as they are inject automatically on the call.

I propose adding an option (true by default):

```go
func RTWithPropagation(propagation bool) RoundTripperOption {
	return func(cfg *roundTripperConfig) {
		cfg.propagation = propagation
	}
}
```

and check this before injecting

```go
        if rt.cfg.propagation {
	    err = tracer.Inject(span.Context(), tracer.HTTPHeadersCarrier(req.Header))
            ...
        }
```

Fixes #1166

2022-04-27 18:24 UTC, ajgajg1134 requested changes
Thanks for submitting a change! Overall this is looking good just one change requested :)

2022-04-27 18:24 UTC, ajgajg1134 commented on contrib/net/http/option.go
> +
Can you add a comment here for this new public function? Perhaps:
`// RTWithPropagation enables/disables propagation for tracing headers. Disabling propagation will disconnect this trace from any downstream traces`

2023-06-29 15:31 UTC, katiehockman submitted a review, later dismissed

2023-06-29 15:33 UTC, ajgajg1134 approved these changes

2023-06-29 15:58 UTC, katiehockman approved these changes

2023-06-29 16:22 UTC, merged