contrib/elastic/go-elasticsearch: Add support for elasticsearch v8
DataDog/dd-trace-go pull request #1363
Opened 2022-06-29 09:26 UTC by xrn

- Removed v6 from directory name
- Deleted tests for Elasticsearch v6
- Added support for v8

2022-06-29 11:31 UTC, xrn commented
@mrkm4ntr as you worked with https://github.com/DataDog/dd-trace-go/pull/1017 - do you have maybe idea why this test is failing?

2022-06-29 20:29 UTC, xrn commented
I was able to solve all test cases but for some reason `TestClientErrorCutoffV8` is still failing. If anyone has any idea I will appreciate.

2022-06-30 09:28 UTC, xrn commented on contrib/elastic/go-elasticsearch.v7/elastictrace_test.go
> +	elasticV8URL = "http://127.0.0.1:9203"
i added `xpack.security.enabled: false` flag not required anymore

2022-07-05 12:49 UTC, xrn commented
@gbbr what do you think? My goal is when ES8 will be merged I want to add support for OpenSearch 2.0 https://github.com/opensearch-project/OpenSearch

2022-07-05 13:19 UTC, gbbr requested changes
Please take a moment to read our contribution guidelines: https://github.com/DataDog/dd-trace-go/blob/main/CONTRIBUTING.md.

For changes, we require an issue to be opened to discuss them. It is not clear to me why we are removing something. Generally we should not. That's a breaking change.

2022-07-05 13:45 UTC, xrn commented
@gbbr Issue added

2022-07-31 18:48 UTC, xrn commented
@gbbr question: Do you know maybe why pull of image https://www.docker.elastic.co/r/elasticsearch/elasticsearch:8.2.0 is working but there are problems with pull https://www.docker.elastic.co/r/elasticsearch/elasticsearch:8.3.0? Should I upgrade something more?

2022-08-01 15:09 UTC, ajgajg1134 commented
Hello! Thanks for putting up a PR for this, instead of dropping the v6 tests I think we should leave them and just add the v8 tests as well. (Since we will continue to provide tracing for v6 although it's worth us including a comment that it's a deprecated version). I'll go through a add some additional comments as well :)

2022-08-11 06:55 UTC, xrn commented
@ajgajg1134 just do confirm with you that we are on the same page.

- In last PR of this type - https://github.com/DataDog/dd-trace-go/pull/1017 - you removed v5 supprt
- Golang is making legacy versions

But here we would like to leave v6 even  deprecated version and I should just add v8?

2022-09-02 19:38 UTC, katiehockman commented
@xrn

> In last PR of this type - https://github.com/DataDog/dd-trace-go/pull/1017 - you removed v5 supprt

The PR description is misleading. We didn’t remove v5 support, we just didn't added new tests for v5 at the time of that PR, since this was the first time we were adding support for elastic search. The PR was saying that it wasn't going to add new tests for something that was already legacy when the support was being introduced.

> For Golang you are making legacy versions as well https://github.com/DataDog/dd-trace-go/pull/1410

Supporting old versions of the language is very different from supporting old versions of a library. We already have a documented policy around language version support. But there’s no need to break backwards compatibility just because something is deprecated, at least not without a migration plan.

> But here we would like to leave v6 even deprecated version and I should just add v8?

Yes. There's no need to delete tests and possibly break backwards compatibility at this time.

2022-09-03 18:16 UTC, xrn commented
@katiehockman thanks for response in next week I will update PR

2022-10-14 11:26 UTC, xrn commented
@katiehockman made some changes, I think it should be fine now. Not sure why but Kafka test are failing, even if I do not introduced any changes. 

FYI I would be in a trip next 2 weeks if you would like to merge earlier feel free to take over the PR

2023-02-23 11:12 UTC, closed without merging