ddtrace/tracer: fixed inconsistency between env and in-code options for single span matching
DataDog/dd-trace-go pull request #1412
Opened 2022-08-04 17:16 UTC by dianashevchenko

Previously:
- using combination of env and in-code options for trace/span sampling rules would result in loss of some rules. For example, in case of using in-code options for span sampling and env variable for trace sampling, trace sampling would prevail and replace all the rules. 
- all the invalid regular expressions are escaped. In that case any invalid regex is still a valid glob. So, added a separate SpanNameServiceRule option to set specifically single span sampling rule of type 2

note:
- using combination of in-code option(WithSamplingRules) and env variables (DD_[TRACE/SPAN]_SAMPLING_RULES) can mess up the order of the indices in error message

2022-08-04 17:20 UTC, dianashevchenko commented
Should probably move the `samplingRulesFromEnv` to `newConfig`, so that in-code option prevails.

2022-08-04 19:21 UTC, ajgajg1134 requested changes

2022-08-05 09:26 UTC, dianashevchenko commented on ddtrace/tracer/rules_sampler.go
> +// Operation and service fields must be valid glob patterns. MaxPerSecond is optional and defaults to infinite, allow all behaviour.
Or maybe this : 
```golang
// SpanNameServiceRule returns a SamplingRule of type SamplingRuleSpan that applies
// the provided sampling rate to all spans matching the operation and service name glob patterns provided.
// Operation and service fields must be valid glob patterns.
func SpanNameServiceRule(name, service string, rate float64) SamplingRule {
	return SamplingRule{
		Service:   globMatch(service),
		Name:      globMatch(name),
		Rate:      rate,
		ruleType:  SamplingRuleSpan,
		exactName: name,
		limiter:   newSingleSpanRateLimiter(0),
	}
}

// SpanNameServiceMPSRule returns a SamplingRule of type SamplingRuleSpan that applies
// the provided sampling rate to all spans matching the operation and service name glob patterns 
// up to the max number of spans per second that can be sampled. 
// Operation and service fields must be valid glob patterns.
func SpanNameServiceMPSRule(name, service string, rate, limit float64) SamplingRule {
	return SamplingRule{
		Service:      globMatch(service),
		Name:         globMatch(name),
		MaxPerSecond: limit,
		Rate:         rate,
		ruleType:     SamplingRuleSpan,
		exactName:    name,
		limiter:      newSingleSpanRateLimiter(limit),
	}
}
```

2022-08-05 12:54 UTC, ajgajg1134 commented on ddtrace/tracer/rules_sampler.go
> +// Operation and service fields must be valid glob patterns. MaxPerSecond is optional and defaults to infinite, allow all behaviour.
That works too!

2022-08-05 15:22 UTC, ajgajg1134 approved these changes
Looks good! 🥳

2022-08-05 15:26 UTC, merged