readme: add an introduction to the repo content
DataDog/dd-trace-go pull request #1465
Opened 2022-09-13 08:47 UTC by Julio-Guerra

Update the readme file so that it introduces the products living in the repository.
It includes some enhancements to the other existing sections which would also need some rework but is out of the scope of this change.

2022-09-13 12:26 UTC, nsrip-dd requested changes
Great idea, thanks Julio! I just have one small suggestion for the profiling item (see comment)

2022-09-13 12:26 UTC, nsrip-dd commented on README.md
> +- [Datadog Go Continuous Profiler](https://docs.datadoghq.com/profiler/): Continuously profile your Go apps to find CPU, memory, and IO bottlenecks, broken down by function name, and line number, to
We don't offer IO profiling (yet), so how about synchronization instead?

```suggestion
- [Datadog Go Continuous Profiler](https://docs.datadoghq.com/profiler/): Continuously profile your Go apps to find CPU, memory, and synchronization bottlenecks, broken down by function name, and line number, to significantly reduce end-user latency and infrastructure costs.  
```

2022-09-13 13:51 UTC, Julio-Guerra commented on README.md
> +- [Datadog Application Security Monitoring (ASM)](https://docs.datadoghq.com/security_platform/application_security/): Get observability into your Go apps attacks that aim to exploit code-level vulne
```suggestion
- [Datadog Application Security Monitoring (ASM)](https://docs.datadoghq.com/security_platform/application_security/): Get observability into your Go apps attacks that aim to exploit code-level vulnerabilities, such as Server-Side-Request-Forgery (SSRF), SQL injection, Log4Shell, and Reflected Cross-Site-Scripting (XSS). ASM is not a standalone Go package and is transparently integrated into the APM tracer. Simply [enable it](https://docs.datadoghq.com/security_platform/application_security/setup_and_configure/?code-lang=go) to make benefit from the security monitoring.
```

2022-09-13 19:39 UTC, nsrip-dd submitted a review, later dismissed

2022-09-22 15:39 UTC, ajgajg1134 requested changes
Just a couple small typos

2022-09-22 15:39 UTC, ajgajg1134 commented on README.md
> +Additionally there are many [contrib](./contrib) packages that can be installed to automatically instrument and trace comonly used Go libraries such as [net/http](https://pkg.go.dev/gopkg.in/DataDog/
```suggestion
Additionally there are many [contrib](./contrib) packages that can be installed to automatically instrument and trace commonly used Go libraries such as [net/http](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http), [gorilla/mux](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux) or [database/sql](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql):
```

2022-09-22 20:03 UTC, ajgajg1134 approved these changes
Looks good to me!

2022-09-26 13:21 UTC, nsrip-dd approved these changes

2022-09-26 13:58 UTC, merged