profiler: add pool to re-use byte slices for profiles
DataDog/dd-trace-go pull request #1660
Opened 2023-01-13 19:09 UTC by nsrip-dd

### What does this PR do?

Add a sync.Pool of byte slices which will contain serialized profiles.
These slices are re-used after a profile is uploaded.

### Motivation

This is mainly motivated by a data race. The fast delta profiler re-uses
a bytes.Buffer for each profile computation. The underlying byte slice
from that buffer is passed on to be uploaded. This is flagged as a race
by the race detector. While delta profile computation and uploading
_shouldn't_ generally happen at the same time, this is still a logical
race.

The simplest fix for this race is to just allocate a new bytes.Buffer
for each delta computation. This PR attempts to address the race
while still avoiding unnecessary allocation.

### Describe how to test/QA your changes

This passes all the existing unit tests under the race detector, including the
ones which failed previously. However, given that this PR kind of mixes a bug
fix and a possible optimization, we should vet it a little more. Maybe in the
reliability environment?

### Reviewer's Checklist

- [x] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [x] Changed code has unit tests for its functionality.
- [x] If this interacts with the agent in a new way, a system test has been added.

2023-01-13 19:11 UTC, nsrip-dd commented
My main concern with the approach of this PR is that it might actually make peak memory use _worse_. If we have N profile types, and keep around ~N byte slices, we might end up with N byte slices, all of which are as large as the largest of the N profiles. Maybe we even want a per-profile byte slice pool? Or maybe we just do the simpler thing and allocate a new bytes.Buffer for each delta profile computation, and accept the increased allocation?

2023-01-13 22:01 UTC, felixge commented
> While delta profile computation and uploading shouldn't generally happen at the same time, this is still a logical race.

I think this could lead to real data corruption if there is a network error on the upload causing a retry.

Anyway, thanks for identifying the root cause of this in slack so quickly. I took a look at the patch, but it seems pretty complicated and maybe even containing a few unnecessary changes.

Can't we just copy the output data from the delta profiler like shown in the diff below? That should fix the issue, is simple, and will only increase memory until the next GC cycle after the upload comes along?

```diff
diff --git a/profiler/profile.go b/profiler/profile.go
index af606d12..7565e72b 100644
--- a/profiler/profile.go
+++ b/profiler/profile.go
@@ -411,7 +411,12 @@ func (fdp *fastDeltaProfiler) Delta(data []byte) (b []byte, err error) {
 	if err = fdp.gzw.Close(); err != nil {
 		return nil, fmt.Errorf("error flushing gzip writer: %v", err)
 	}
-	return fdp.buf.Bytes(), nil
+
+	// Copy fdp.buf data to avoid a data race with uploading the previous delta
+	// profile which might require retrying in the case of network errors.
+	out := make([]byte, fdp.buf.Len())
+	copy(out, fdp.buf.Bytes())
+	return out, nil
 }
 
 type comparingDeltaProfiler struct {
```

2023-01-13 22:01 UTC, felixge requested changes
> While delta profile computation and uploading shouldn't generally happen at the same time, this is still a logical race.

I think this could lead to real data corruption if there is a network error on the upload causing a retry.

Anyway, thanks for identifying the root cause of this in slack so quickly. I took a look at the patch, but it seems pretty complicated and maybe even containing a few unnecessary changes.

Can't we just copy the output data from the delta profiler like shown in the diff below? That should fix the issue, is simple, and will only increase memory until the next GC cycle after the upload comes along?

```diff
diff --git a/profiler/profile.go b/profiler/profile.go
index af606d12..7565e72b 100644
--- a/profiler/profile.go
+++ b/profiler/profile.go
@@ -411,7 +411,12 @@ func (fdp *fastDeltaProfiler) Delta(data []byte) (b []byte, err error) {
 	if err = fdp.gzw.Close(); err != nil {
 		return nil, fmt.Errorf("error flushing gzip writer: %v", err)
 	}
-	return fdp.buf.Bytes(), nil
+
+	// Copy fdp.buf data to avoid a data race with uploading the previous delta
+	// profile which might require retrying in the case of network errors.
+	out := make([]byte, fdp.buf.Len())
+	copy(out, fdp.buf.Bytes())
+	return out, nil
 }
 
 type comparingDeltaProfiler struct {
```

2023-01-13 22:47 UTC, nsrip-dd reviewed
Agreed, this change is trying to avoid the performance hit of copying the buffer. But for the sake of fixing the bug, I'll take the simpler approach in this PR.

I do think it's worth considering as a followup optimization. For example, the CPU profile allocates a new slice every time. But maybe it doesn't need to?

2023-01-14 11:52 UTC, felixge approved these changes
LGTM.

> Agreed, this change is trying to avoid the performance hit of copying the buffer. But for the sake of fixing the bug, I'll take the simpler approach in this PR.

👍 

> I do think it's worth considering as a followup optimization. For example, the CPU profile allocates a new slice every time. But maybe it doesn't need to?

Intuitively I don't think optimizing this is worth the extra complexity. But I figured it's worth taking a quick measurement.

I decided to benchmark the time it takes to allocate, copy and GC a 1MB byte slice.

```
name     time/op
Copy-10  75.9µs ± 7%
```

Considering that this is the cost per MB that we'll only pay once per 60s, I don't think this will produce noticeable (or even measurable) overhead in practice. The allocs might show up on the alloc profile, but even there a few MBs of allocs will usually be drowned by other program activity.

The code and compiler output can be found here: https://godbolt.org/z/q35qxzznK

![CleanShot 2023-01-14 at 12 33 37@2x](https://user-images.githubusercontent.com/15000/212469870-e5ec7261-6cd4-4e95-ad54-88c4dc356deb.png)

2023-01-14 13:38 UTC, nsrip-dd commented
Thanks for the measurement! 🙇 I'm convinced the optimization isn't worth the complexity.

2023-01-14 13:41 UTC, merged