ddtrace/internal: fix race with internal.Testing
DataDog/dd-trace-go pull request #1703
Opened 2023-01-30 16:36 UTC by knusbaum

This forces internal.Testing to be associated with a specific tracer instance, and eliminates data races setting global values.

Fixes #1700

### What does this PR do?

### Motivation

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2023-02-01 17:03 UTC, dianashevchenko requested changes
A few nits, LGTM

2023-02-01 17:03 UTC, dianashevchenko commented on ddtrace/internal/globaltracer.go
> +// SetGlobalTracer sets the global tracer to t. testing is set to true when the mock tracer is
```suggestion
// SetGlobalTracer sets the global tracer to t.testing is set to true when the mock tracer is
```

2023-02-22 20:10 UTC, knusbaum commented on ddtrace/internal/globaltracer.go
> +}
```suggestion
func Testing() bool {
	if gt := globalTracer.Load().(*tracerCfg); gt != nil {
		return gt.testing
	}
	return false
}
```

2023-07-26 13:45 UTC, dianashevchenko approved these changes

2023-10-03 01:20 UTC, closed without merging