contrib/echo: wrap appsec error in echo.HTTPError
DataDog/dd-trace-go pull request #1744
Opened 2023-02-17 16:20 UTC by Hellzy

### What does this PR do?
This change ensures that the error returned by the appsec echo middleware is always an `echo.HTTPError`.
This is needed so that the top level APM code doesn't override the response status span tag with `500`, which
happens if it encounters any other error type than `echo.HTTPError`

### Motivation
This fixes a bug spotted while enabling user blocking system-tests.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2023-02-17 17:00 UTC, eliottness approved these changes

2023-02-17 17:01 UTC, eliottness commented
Can we have a link to the test/job failing because of this maybe ?

2023-02-17 21:14 UTC, Julio-Guerra requested changes
Glad you caught this before release 👏
It still needs a test to reproduce and confirm the fix please, if you could add it 🙏
Also, I think this simple handler isn't handled properly by you post-handler error management:

```go
func myHandler(ctx echo.Context) error {
    return errors.New("my error without any response")
}
```
where you might end up with the expected behaviour by chance but our monitored HTTP status code will be `0`, while it will actually be 500 if I understood correctly echo's behaviour.

2023-02-20 15:29 UTC, Hellzy commented
> Glad you caught this before release clap It still needs a test to reproduce and confirm the fix please, if you could add it pray Also, I think this simple handler isn't handled properly by you post-handler error management:
> 
> ```go
> func myHandler(ctx echo.Context) error {
>     return errors.New("my error without any response")
> }
> ```
> 
> where you might end up with the expected behaviour by chance but our monitored HTTP status code will be `0`, while it will actually be 500 if I understood correctly echo's behaviour.

What changed:
We now call the echo error handlers (`echo.Context.Error()`) when the middleware returns an error. This provides several benefits:
- The response status gets committed
- We can simplify our wrapper around the response writer to simply expose `Status()`
- We are guaranteed to follow APM's behaviour when it comes to status code handling
- We don't get in the way of users that want echo to generate the response/status code for them and simply return custom errors (i.e we let echo handle this directly and just read the result).

2023-02-20 15:34 UTC, Julio-Guerra approved these changes

2023-02-20 15:56 UTC, merged