internal/appsec: use latest HTML blocked response template
DataDog/dd-trace-go pull request #1952
Opened 2023-05-02 09:03 UTC by Hellzy

### What does this PR do?
Update the HTML template used for default blocked responses to the latest version.

### Motivation
This latest version removes an UTF-8 character from the template, making it ASCII only.

### Describe how to test/QA your changes

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2023-05-02 12:16 UTC, Julio-Guerra approved these changes

2023-05-02 12:17 UTC, Julio-Guerra commented
Let's enable the corresponding system test

2023-05-02 12:18 UTC, Julio-Guerra requested changes
Let's enable the corresponding system test

2023-05-30 09:36 UTC, Hellzy commented
Here is the system-tests run with the newly enabled tests: https://github.com/DataDog/dd-trace-go/actions/runs/5119915706.
@Julio-Guerra I also updated the json template to be minified as was agreed upon in the libraries discussion.

2023-05-30 09:43 UTC, Julio-Guerra approved these changes

2023-05-30 10:08 UTC, merged