Add rpc non error func option
DataDog/dd-trace-go pull request #2035
Opened 2023-06-12 18:11 UTC by BIwashi

### What does this PR do?

This PR adds a new option called `NonErrorFunc` which allows users to set a custom function to determine whether an error should not be considered as an error for tracing purposes before sending it to DataDog.

### Motivation

There are cases where an application produces errors, but they should not be sent to DataDog as errors. While the `NonErrorCodes` option allows for not treating specific gRPC status codes as errors, there are use cases where a more granular decision is needed based on the specific error, rather than just the status code.
For example, a user might want to consider a NotFound error as non-error for a specific RPC.

example
```go
opts = []rpc.Option{
	...
	rpc.WithUnaryInterceptors(
		ddgrpc.UnaryServerInterceptor(
			ddgrpc.NonErrorFunc(func(method string, err error) bool {
				if err == nil {
					return true
				}
				errCode := status.Code(err)
				if errCode == codes.NotFound && method == "/example.ExampleService/GetInfo" {
					return true
				}
				return false
			}),
		),
	),
	...
}
...
rpcServer = rpc.NewServer(rpcHandler, opts...)

```

### Describe how to test/QA your changes

Unit tests are included.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2023-07-10 14:25 UTC, dianashevchenko commented
Hi @BIwashi, thank you for the contribution! I think it wouldn't hurt to add some unit tests covering the `NonErrorFunc` option.

2023-07-10 14:25 UTC, dianashevchenko requested changes
Hi @BIwashi, thank you for the contribution! I think it wouldn't hurt to add some unit tests covering the `NonErrorFunc` option.

2023-07-12 18:06 UTC, BIwashi commented
@dianashevchenko 
I added unit tests for the `NonErrorFunc option`!
https://github.com/DataDog/dd-trace-go/pull/2035/commits/50c90b20490aa876cdbcaebc1cd02038953e7d63
How does this implementation look to you? I would appreciate your feedback.

2023-07-25 15:08 UTC, dianashevchenko requested changes

2023-10-31 14:59 UTC, ajgajg1134 requested changes
See comment on proposal here: https://github.com/DataDog/dd-trace-go/issues/2043#issuecomment-1787390253

2023-12-05 07:13 UTC, BIwashi commented on contrib/google.golang.org/grpc/stats_server.go
> +	}
You are correct, finishWithError needs to be called. I made a mistake. Thanks.
I fixed it.

https://github.com/DataDog/dd-trace-go/pull/2035/commits/5b83467f878be33173e8a755726d82b9586fd2e2

2023-12-05 07:15 UTC, BIwashi commented on contrib/google.golang.org/grpc/grpc_test.go
> +				}
Thank you so much!
I fixed it.
https://github.com/DataDog/dd-trace-go/pull/2035/commits/6a3227efb83a2ca1ed60996dd6b6824815e36158

2023-12-05 07:18 UTC, BIwashi commented on contrib/google.golang.org/grpc/grpc_test.go
> +		defer mt.Stop()
Is this the correct revision of your point?
https://github.com/DataDog/dd-trace-go/pull/2035/commits/4fca22416cf9726a6cb7943f58a39941a7b5b5a3

2023-12-05 07:20 UTC, BIwashi commented on contrib/google.golang.org/grpc/option.go
> +
I have renamed the function name and config field names considering [this comment](https://github.com/DataDog/dd-trace-go/pull/2035#pullrequestreview-1706536768) as well. Thanks!
https://github.com/DataDog/dd-trace-go/pull/2035/commits/100083f78905ea0f4530597d88c8bf31e4cb8848

2023-12-05 07:24 UTC, BIwashi commented on contrib/google.golang.org/grpc/stats_client.go
> +		finishWithError(span, rs.Error, fullMethod, h.cfg)
I fixed it, too.
https://github.com/DataDog/dd-trace-go/commit/5b83467f878be33173e8a755726d82b9586fd2e2

2023-12-05 07:25 UTC, BIwashi commented
I apologize for the delay in making the corrections. It would be much appreciated if you could take the time to review the revisions again. 
@dianashevchenko cc @ajgajg1134

2024-08-23 14:25 UTC, darccio approved these changes

2025-03-10 16:21 UTC, darccio commented
@rarguelloF Can we review this PR?

2025-11-21 11:32 UTC, darccio commented
@rarguelloF For our internal review backlog 😅

2026-07-22 13:40 UTC, darccio commented
Closing in favour of #5057.

2026-07-22 13:40 UTC, closed without merging