contrib/emicklei/go-restful/v3: add integration for newest version
DataDog/dd-trace-go pull request #2088
Opened 2023-06-29 14:20 UTC by michaelbeaumont

### What does this PR do?

Adds support for the [latest version of `go-restful`](https://github.com/emicklei/go-restful#using-go-modules).

### Motivation

The motivation for previous versions can't be used with `v3`.

### Reviewer's Checklist

- [x] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2023-06-29 15:36 UTC, rarguelloF requested changes
@michaelbeaumont 👋 Thanks for your contribution!
Component name needs to be updated, everything else LGTM.

2023-06-29 15:44 UTC, michaelbeaumont commented on contrib/emicklei/go-restful/v3/restful.go
> +const componentName = "emicklei/go-restful"
done!

2023-06-30 15:13 UTC, rarguelloF commented
@michaelbeaumont there are some linter errors, could you take a look? 🙏 
https://github.com/DataDog/dd-trace-go/actions/runs/5420976820/jobs/9856100211?pr=2088

2023-06-30 16:15 UTC, michaelbeaumont commented
> @michaelbeaumont there are some linter errors, could you take a look? 🙏 https://github.com/DataDog/dd-trace-go/actions/runs/5420976820/jobs/9856100211?pr=2088

Done

2023-07-03 10:06 UTC, rarguelloF approved these changes

2023-07-03 20:39 UTC, katiehockman approved these changes

2023-07-03 20:44 UTC, merged