Adding LoadOptionsFunc implementation
DataDog/dd-trace-go pull request #2095
Opened 2023-07-05 13:56 UTC by dcarbone

### What does this PR do?

Addresses #2094 by adding a `WithDataDogTracer` func that adheres to the AWS SDK Go V2 `config.LoadOptionFunc` type.

### Motivation

I need to be able to configure the DD Tracer without directly having access to a config type.

### Describe how to test/QA your changes

It functions identically to the current `AppendMiddleware` func, but appends to the `APIOptions` present on the `LoadOptions` type instead of the config type directly.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2026-08-04 15:51 UTC, darccio commented
@codex review

2026-08-05 14:51 UTC, darccio requested changes

2026-08-05 14:51 UTC, darccio commented on contrib/aws/aws-sdk-go-v2/aws/aws.go
> +}
`prepConfig(opts...)` runs once when `WithDataDogTracer(...)` is called, and the resulting `*config` is captured by the closure. If the returned `LoadOptionsFunc` value is stored and reused across multiple `LoadDefaultConfig` calls, `defaults()` never re-reads the global analytics-rate default after the first call — it stays pinned to whatever it was at construction time. `AppendMiddleware` doesn't have this issue because it calls `prepConfig` fresh on every invocation.

Moving the `prepConfig` call inside the closure would match `AppendMiddleware`'s per-call recomputation and remove the staleness edge case, at the cost of re-applying `opts` on every load:

```suggestion
func WithDataDogTracer(opts ...Option) awsconfig.LoadOptionsFunc {
	return func(o *awsconfig.LoadOptions) error {
		appendMiddleware(prepConfig(opts...), &o.APIOptions)
		return nil
	}
}
```

cc @rarguelloF

2026-08-05 17:43 UTC, darccio requested changes
Some minor request change

2026-09-02 15:10 UTC, darccio commented on contrib/aws/aws-sdk-go-v2/aws/example_test.go
> +	awsCfg, err := awscfg.LoadDefaultConfig(context.Background(), awstrace.WithDataDogTracer())
Fixed in 28ebd5b (renamed to `ExampleWithDataDogTracer`), though that commit left the example referencing undefined `err`/`awsCfg` — the actual `LoadDefaultConfig` call got dropped in the process. Restored in 75792a1d3, so the example now compiles and is correctly associated with `WithDataDogTracer`.

2026-09-02 15:10 UTC, darccio commented on contrib/aws/aws-sdk-go-v2/aws/aws_test.go
> +			})
Fixed in 28ebd5b — capturing `err` from `SendMessage` and asserting it against `tt.expectedStatusCode` (error on >=400, no error otherwise), `TODO` removed.

2026-09-02 15:10 UTC, darccio commented on contrib/aws/aws-sdk-go-v2/aws/aws_test.go
> +	}
Fixed in 75792a1d3 — removed the unused `responseStatus` field from the test table.

2026-09-02 15:25 UTC, darccio commented
@codex review

2026-09-02 15:26 UTC, darccio commented
I'm doing some cleaning, so I took over this PR.

2026-09-02 15:37 UTC, darccio commented on contrib/aws/aws-sdk-go-v2/aws/aws.go
> +func WithDataDogTracer(opts ...Option) awsconfig.LoadOptionsFunc {
Not adding a CONTRIBUTING.md entry for this. That file is repo-wide process/tooling docs (PR conventions, CI, `make` targets, module management, benchmarks) and its Integrations section explicitly delegates integration-specific docs to contrib/README.md instead. That contract requires a package doc comment + `example_test.go`, which `WithDataDogTracer` already has (aws.go:70-73, ExampleWithDataDogTracer in example_test.go).

This also matches existing precedent: `AppendMiddleware` (the sibling function in this same file) has no CONTRIBUTING.md entry, and other contrib packages with the same 'return the instrumented library's own option/config type' pattern (e.g. `contrib/twmb/franz-go`'s `WithTracing(...) kgo.Opt`, `contrib/mark3labs/mcp-go`'s `WithMCPServerTracing(...) server.ServerOption`) aren't documented there either. AGENTS.md's CONTRIBUTING.md-update bar for 'a new method of interacting with/customizing the tracer' is aimed at core tracer-configuration mechanisms (new DD_* config sources, new make flags, new CI workflows) — not routine per-integration API additions following an established contrib pattern.

2026-09-02 15:38 UTC, darccio commented
/gardener shadow

2026-09-02 16:49 UTC, darccio commented
/gardener shadow

2026-09-03 07:05 UTC, darccio commented
/gardener shadow

2026-09-03 14:44 UTC, darccio approved these changes

2026-09-10 14:42 UTC, darccio commented
Hey @dcarbone @rarguelloF — I dug into the Orchestrion compilation loop reported on this PR and pushed a fix for it directly to this branch. Wanted to explain what I found and why the fix looks the way it does.

## What's hanging

`Build Metrics (aws.v2, orchestrion)` was stuck `in_progress` far past its normal ~5–20 min ceiling (I saw it well past 1h40m before it eventually got killed). Reproduced locally: running `go build -toolexec='orchestrion toolexec' ./aws.v2/...` against this branch never completes — `ps` shows two separate `orchestrion toolexec ... compile ... -p github.com/aws/aws-sdk-go-v2/config` processes running concurrently against the same buildid, i.e. Orchestrion is recursively re-triggering a build of `aws-sdk-go-v2/config` while trying to weave it.

## Why

`contrib/aws/aws-sdk-go-v2/aws/orchestrion.yml` already has `Config`/`*Config` aspects that wrap **every** `aws.Config{}` construction, including the one built internally by `aws-sdk-go-v2/config`'s own `resolveDefaultAWSConfig` (`*cfg = aws.Config{...}` in `resolve.go`). So weaving already injects an edge today: `aws-sdk-go-v2/config → contrib/aws` (via the injected `awstrace.AppendMiddleware` call).

`WithDataDogTracer` adds a direct import of `github.com/aws/aws-sdk-go-v2/config` into that same `contrib/aws` package (to reference `LoadOptionsFunc`/`LoadOptions`). That closes the cycle: `aws-sdk-go-v2/config → contrib/aws → aws-sdk-go-v2/config`. This cycle only exists after weaving — it's never present in the unwoven source, so Go's own import-cycle detector never gets a chance to catch it. Instead, Orchestrion's weaving/dependency resolution appears to spin on it, which is exactly the hang.

## The fix

I moved `WithDataDogTracer` out of `contrib/aws/aws-sdk-go-v2/aws` into a new leaf package, `contrib/aws/aws-sdk-go-v2/aws/awsconfig`, which imports both `aws-sdk-go-v2/config` and the parent `aws` package's public `AppendMiddleware`. That keeps the woven `aws` package free of any dependency on `aws-sdk-go-v2/config`, so weaving can't fold it back into a cycle.

This isn't a new pattern in this repo — it mirrors what `contrib/cloud.google.com/go/pubsubtrace` and `contrib/segmentio/kafka-go/internal/tracing` already do for the same class of weaving-induced import cycle (see the doc comments on those packages).

Concretely:
- `WithDataDogTracer(opts ...aws.Option) config.LoadOptionsFunc` now lives in `contrib/aws/aws-sdk-go-v2/aws/awsconfig`, calling the parent package's `AppendMiddleware` under the hood.
- `contrib/aws/aws-sdk-go-v2/aws/aws.go` no longer imports `aws-sdk-go-v2/config`.
- Moved/updated the relevant tests (`TestWithDataDogTracer*`) and the example (`ExampleWithDataDogTracer`) to the new package/import path.
- No behavior change to `AppendMiddleware` or any existing aspect-based auto-instrumentation (verified the existing `internal/orchestrion/_integration/aws.v2` suite, including `TestLoadDefaultConfig`, still passes against real containers).

I confirmed the loop is gone: a cold-cache `orchestrion toolexec` build of `./aws.v2/...` that previously never finished (killed after 4+ min via `timeout`) now completes cleanly in ~26s with this change.

Only trade-off is the import path for the new helper changes from `aws.WithDataDogTracer` to `awsconfig.WithDataDogTracer` — happy to discuss alternate naming/placement if you'd prefer something else, but wanted to get the CI-blocking hang fixed first. Let me know if you want any adjustments!

2026-09-10 14:54 UTC, darccio commented
Fixed the `check-modules` CI failure: moving `WithDataDogTracer` out of `contrib/aws/aws-sdk-go-v2/aws` (previous commit) left `orchestrion/all/go.mod` with unused indirect deps on `aws-sdk-go-v2/config` and its sub-dependencies, since that module only imports the woven `aws` package (not the new `awsconfig` helper, which has no aspects). Regenerated via `scripts/fix_modules.sh` — `check-modules` is green now.

2026-09-11 11:53 UTC, rarguelloF approved these changes

2026-09-15 13:46 UTC, merged

2026-09-15 14:08 UTC, darccio commented
This will be released as part of `v2.12.0`. Our current release `v2.11.0` (trackable at https://github.com/DataDog/dd-trace-go/issues/5359) started before this was merged.