contrib/labstack/echo.v4: add WithErrorTranslator Option
DataDog/dd-trace-go pull request #2169
Opened 2023-08-09 19:33 UTC by mattscamp

### What does this PR do?

Adds a `WithErrorTranslator` Option that allows defining a translator of custom errors to the required format.

### Motivation

We use a custom error type across our company that cannot be translated to an `echo.HTTPError` which results in all our status codes set as 500.
 
### Reviewer's Checklist
- [x] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.

2023-08-21 15:40 UTC, mattscamp commented
Hey @ahmed-mez , if there is anything I can do to expedite this PR, let me know!

2023-08-23 08:05 UTC, ahmed-mez commented
Hey @mattscamp - thanks for the contribution! The PR is triaged and the corresponding team will review in the coming days.
cc @rarguelloF

2023-08-31 14:46 UTC, zarirhamza commented on contrib/labstack/echo.v4/option.go
> +	cfg.customErrorFunc = func(err error) *echo.HTTPError { return nil }
Also we should document in the comments here that by default we do no translation which is why we're setting the value to nil.

2023-08-31 14:47 UTC, zarirhamza requested changes
Few quick naming and documentation changes and after should be good

2023-08-31 15:24 UTC, zarirhamza approved these changes

2023-08-31 15:31 UTC, rarguelloF reviewed
Thanks for the contribution! @mattscamp

After reviewing with @zarirhamza, we just came up with a few minor changes to simplify the code a little bit and make the name of the option a little bit more descriptive. Once these few changes are made, it should be good to go.

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/echotrace.go
> +				if echoErr != nil || errors.As(err, &echoErr) {
```suggestion
				if echoErr, ok := cfg.translateError(err); ok {
```

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/echotrace_test.go
> +func TestCustomErrorFunc(t *testing.T) {
```suggestion
func TestWithErrorTranslator(t *testing.T) {
```

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/echotrace_test.go
> +	}
```suggestion
	translateError := func(e error) (*echo.HTTPError, bool) {
		return &echo.HTTPError{
			Message: e.(*testCustomError).Error(),
			Code:    e.(*testCustomError).TestCode,
		}
	}, true
```

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/option.go
> +	cfg.customErrorFunc = func(err error) *echo.HTTPError { return nil }
```suggestion
	cfg.translateError = func(err error) (*echo.HTTPError, bool) {
               var echoErr *echo.HTTPError
               if errors.As(err, &echoErr) {
                       return echoErr, true
               }
               return nil, false
       }
```

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/option.go
> +type CustomErrorFunc func(err error) *echo.HTTPError
```suggestion
```

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/option.go
> +	customErrorFunc   CustomErrorFunc
```suggestion
	translateError    func(err error) (*echo.HTTPError, bool)
```

2023-08-31 15:31 UTC, rarguelloF commented on contrib/labstack/echo.v4/option.go
> +func WithCustomErrorFunc(customErrorFunc CustomErrorFunc) Option {
```suggestion
// WithErrorTranslator sets a function to translate Go errors into echo Errors.
// This is used for extracting the HTTP response status code.
func WithErrorTranslator(fn func(err error) (*echo.HTTPError, bool)) Option {
```

2023-09-05 20:47 UTC, mattscamp commented
Thanks @rarguelloF @zarirhamza - made those suggested updates!

2023-09-05 20:57 UTC, zarirhamza approved these changes
LGTM

2023-09-07 10:08 UTC, rarguelloF approved these changes

2023-09-07 14:35 UTC, ajgajg1134 approved these changes
Looks good to me! Thanks!!

2023-09-07 15:20 UTC, merged