profiler: remove WithAPIKey
DataDog/dd-trace-go pull request #2224
Opened 2023-09-19 15:46 UTC by JianyiGao

### What does this PR do?
Remove `WithAPIKey` option 
https://github.com/DataDog/dd-trace-go/issues/866

### Motivation
TLDR: 
Agentless uploading is originally supported if customer set `DD_API_KEY` env variable, or use `WithAPIKey` option. 

Due to business reasons we want to deprecate agentless support for public uses, only allow internal usage by explicitly using `WithAgentlessUpload` option and set `DD_API_KEY` env variable. 

This PR is to fully remove `WithAPIKey` option.

Related Change: https://github.com/DataDog/dd-trace-go/pull/906/ 
More context: [Agentless vs Agent Uploading](https://docs.google.com/document/d/172cmlRA_GTSu2OjC_FL5PzO6EjCpRH5ddU1nP08-yF0/editl)

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2023-09-20 07:12 UTC, felixge requested changes
This is a breaking API change. Please ping me in slack to provide more context on this. Thanks!

cc @nsrip-dd

2023-09-21 08:43 UTC, darccio approved these changes

2023-09-21 09:32 UTC, felixge approved these changes

2023-09-21 09:32 UTC, felixge commented on profiler/options.go
>  // WithAgentlessUpload is currently for internal usage only and not officially
While we're at it, I think we should probably remove `WithAgentlessUpload` and replace it with an environment variable as well?

2023-09-22 11:59 UTC, felixge commented on profiler/options.go
>  	}
NIT: Isn't this the same as `c.agentless = internal.BoolEnv("DD_PROFILING_AGENTLESS", false)`?

2023-09-22 12:00 UTC, felixge approved these changes
LGTM

2023-09-25 15:44 UTC, merged