WIP: fix dbm - apm linking when using peer.service
DataDog/dd-trace-go pull request #2233
Opened 2023-09-26 09:51 UTC by rarguelloF

### What does this PR do?

### Motivation

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2023-09-28 12:15 UTC, amarziali approved these changes
the logic looks good

2023-09-28 17:10 UTC, alexandre-normand approved these changes
Thanks for the fix, @rarguelloF . This looks good to me. 

The only concern / improvement we could imagine is the one we discussed the other day where we'd have the `contrib/database/sql` package do the classic pattern of:
* start a span
* execute operation
* finish the span. 

This relates to this relatively [old issue](https://github.com/DataDog/dd-trace-go/pull/336) with the optional driver API/methods and we were curious if, now that those APIs are probably implemented in most drivers, we could get away with going back to that pattern. Of course, this change would need to happen in order for this fix to get simplified but I wanted to bring this up in case the Go tracer team was looking for more examples/motivation to refactor this code.

2023-10-03 12:25 UTC, dianashevchenko requested changes

2023-10-03 12:25 UTC, dianashevchenko commented on ddtrace/tracer/sqlcomment.go
> +	if peerService, _ := getPeerServiceFromSource(c); peerService != "" {
I ran go test with coverage, this function is only covered by tests lines 89 to 94. I suggest writing a small test, or adding more test cases in `TestSQLCommentCarrier`.

2023-10-03 12:25 UTC, dianashevchenko commented on ddtrace/tracer/sqlcomment.go
> +	}
Suggestion of the code flow, if we are getting the tracer insance, we might as well see if the peerServiceDefaultsEnabled is 'true' right away. Thoughts?
```suggestion
	if tr, ok := internal.GetGlobalTracer().(*tracer); !ok || !tr.config.peerServiceDefaultsEnabled {
		return dbService
	}
	if peerService, _ := c.getMeta(ext.PeerService); peerService != "" {
		return peerService
	}
	
```

2023-10-03 12:25 UTC, dianashevchenko commented on ddtrace/tracer/spancontext.go
> +type spanMetaGetter interface {
nit: I would suggest renaming the interface to metaProvider or smth like that

2023-10-03 12:25 UTC, dianashevchenko commented on contrib/database/sql/propagation_test.go
> +		executed       []*regexp.Regexp
Can you please elaborate what are the changes in testing about? I see that they don't touch the code changed in ddtrace/tracer files

2023-11-27 09:40 UTC, closed without merging