feat(dyngo): major refactor of dyngo package
DataDog/dd-trace-go pull request #2394
Opened 2023-11-28 11:06 UTC by RomainMuller

### What does this PR do?

### Motivation

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2024-01-11 08:57 UTC, Julio-Guerra commented on internal/appsec/dyngo/operation.go
> +	self() *operation
Nice simplification indeed 👏
But while I was reading its use in the code, I was thinking `o.implementation()` or `o.unwrap()` might be more understandable maybe:
```suggestion
	 unwrap() *operation
```

No strong opinion here.

2024-01-11 08:57 UTC, Julio-Guerra commented on internal/appsec/dyngo/operation.go
>  }
Worth some rationals on how this will work :-)

2024-01-12 08:32 UTC, Hellzy reviewed
Cool rework!

 ̶I̶'̶m̶ ̶t̶h̶i̶n̶k̶i̶n̶g̶ ̶w̶e̶ ̶c̶a̶n̶ ̶g̶e̶t̶ ̶r̶i̶d̶ ̶o̶f̶ ̶I̶s̶A̶r̶g̶O̶r̶f̶/̶I̶s̶R̶e̶s̶u̶l̶t̶O̶f̶ ̶i̶m̶p̶l̶e̶m̶s̶ ̶o̶v̶e̶r̶a̶l̶l̶ ̶a̶n̶d̶ ̶j̶u̶s̶t̶ ̶u̶s̶e̶ ̶t̶h̶e̶ ̶i̶n̶t̶e̶r̶f̶a̶c̶e̶s̶ ̶t̶o̶ ̶e̶n̶f̶o̶r̶c̶e̶ ̶t̶y̶p̶e̶ ̶c̶o̶n̶s̶t̶r̶a̶i̶n̶t̶,̶ ̶l̶e̶t̶ ̶m̶e̶ ̶k̶n̶o̶w̶ ̶w̶h̶a̶t̶ ̶y̶o̶u̶ ̶t̶h̶i̶n̶k̶.̶ ̶M̶a̶i̶n̶l̶y̶ ̶i̶t̶ ̶j̶u̶s̶t̶ ̶r̶e̶m̶o̶v̶e̶s̶ ̶t̶h̶e̶ ̶n̶e̶e̶d̶ ̶t̶o̶ ̶i̶m̶p̶l̶e̶m̶e̶n̶t̶ ̶t̶h̶o̶s̶e̶ ̶e̶m̶p̶t̶y̶ ̶f̶u̶n̶c̶t̶i̶o̶n̶s̶ ̶f̶o̶r̶ ̶e̶a̶c̶h̶ ̶a̶r̶g̶/̶r̶e̶s̶ ̶t̶y̶p̶e̶

Other than that LGTM, spotted a few exported funcs that could use a description for consistency.

EDIT: scratch that first part, making it work would do more harm than good

2024-01-12 08:32 UTC, Hellzy commented on internal/appsec/waf.go
> +func AddWAFEventListener(fn wafEventListener) {
Nit: short description to keep exported functions documented

2024-01-12 08:32 UTC, Hellzy commented on internal/appsec/listener/grpcsec/grpc.go
> +func Install(wafHandle *waf.Handle, actions sharedsec.Actions, cfg *config.Config, lim limiter.Limiter, root dyngo.Operation) {
Nit: short description to keep exported functions documented

2024-01-12 08:32 UTC, Hellzy commented on internal/appsec/dyngo/operation.go
> +func EmitData[T any](op Operation, data T) {
Nit: description to keep exported functions documented.
Sorry that one is on me 🙈

2024-01-12 08:32 UTC, Hellzy commented on internal/appsec/dyngo/operation.go
> +// This is the one true Operation implementation!
All hail 🙏

2024-01-29 21:36 UTC, katiehockman approved these changes
Didn't review the appsec code, but I don't see any major changes in `contrib` other than using a different package, so I'll trust that others have reviewed the rest.

2024-02-05 12:09 UTC, Julio-Guerra requested changes

2024-02-05 12:09 UTC, Julio-Guerra commented on internal/appsec/dyngo/operation.go
> +func Finish[O Operation, E ResultOf[O]](op O, results E) {
`StartOperation` vs `Finish`: do you want to align both?

2024-02-06 08:45 UTC, Julio-Guerra approved these changes

2024-02-06 08:46 UTC, Julio-Guerra commented
Congrats - major API change embracing the Go generics the right way 👏 This was envisioned in the original PR design as a major improvement :-)

2024-02-06 08:50 UTC, RomainMuller commented
/merge

2024-02-06 08:55 UTC, Julio-Guerra approved these changes

2024-02-06 08:55 UTC, merged