chore(otel): adds an API for generating span links
DataDog/dd-trace-go pull request #2614
Opened 2024-03-13 15:47 UTC by mabdinur

### What does this PR do?

Adds `AddLink` to the span struct.

### Motivation

Currently span links can only be set on spans on span creation (via [WithSpanLinks](https://github.com/DataDog/dd-trace-go/blob/v1.999.0-rc.8/ddtrace/tracer/option.go#L414) option). To support many use cases we need the ability to add SpanLinks after a span has been created.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

2024-03-13 15:49 UTC, mabdinur commented on ddtrace/tracer/span.go
> +	// TODO: Add support for setting tracestate and traceflags
```suggestion
	// TODO: Add support for setting tracestate
```

2024-03-14 13:54 UTC, mabdinur commented
@dianashevchenko Do I also need to update mockspan.go?

2024-03-15 12:51 UTC, dianashevchenko requested changes
Nits

2024-03-15 12:51 UTC, dianashevchenko commented on ddtrace/tracer/span.go
> +	//  traceIDUpper uint64
This comment should be either expanded or removed

2024-03-15 12:51 UTC, dianashevchenko commented on ddtrace/tracer/span.go
> +	// TODO: Add support for setting tracestate
Is it still a todo?

2024-03-15 12:52 UTC, dianashevchenko commented
@mabdinur just remembered this change should probably be reflected in the opentelemetry package as well. Since, OTel API does have the AddLink method, which we couldn't support before.

2024-03-15 15:45 UTC, mabdinur commented
> @mabdinur just remembered this change should probably be reflected in the opentelemetry package as well. Since, OTel API does have the AddLink method, which we couldn't support before.

I am not sure if the Otel API exposes an AddLink method: https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/trace.go#L338. I think adding links to existing spans is a concept internal to go sdk: https://github.com/open-telemetry/opentelemetry-go/blob/da047e70ef583efbc91883dd2e35c616569260ef/sdk/trace/span.go#L632C25-L632C32.

2024-03-18 13:44 UTC, dianashevchenko commented
@mabdinur yes, I think you're right. Even better then.

@darccio the PR looks good to me, but feel free to review.

2024-03-18 13:45 UTC, dianashevchenko commented
@mabdinur please address my previous comments before marking the conversation as resolved 🙌

2024-03-21 23:00 UTC, merged