contrib/jackc/pgx.v5: publish pgxpool stats to statsd client
DataDog/dd-trace-go pull request #2692
Opened 2024-05-11 16:33 UTC by bengentree

Fixes #2680

### What does this PR do?

Adds a new option to contrib/jackc/pgx.v5  to enable polling and submission of pgxpool stats as metrics to Datadog
Ref: https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Stat

### Motivation

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

Unsure? Have a question? Request a review!

2024-05-13 18:49 UTC, mtoffl01 commented on contrib/jackc/pgx.v5/metrics.go
> +	AcquireCount            = tracerPrefix + "pgx.pool.connections.acquire"
All the metrics should be prefixed with `datadog.tracer.`

2024-05-14 15:24 UTC, mtoffl01 requested changes

2024-05-14 15:24 UTC, mtoffl01 commented on contrib/jackc/pgx.v5/metrics.go
> +	}
We can remove lines 38 - 41 as they essentially duplicate the `err != nil` check done by the caller, `NewPoolWithConfig` (Note: We also removed a similar check in the database/sql DB Stats feature in more recent versions , [PR](https://github.com/DataDog/dd-trace-go/pull/2682/files))

2024-07-09 16:19 UTC, mtoffl01 approved these changes

2024-07-10 08:09 UTC, darccio approved these changes

2024-07-10 08:39 UTC, darccio commented
@rarguelloF @zarirhamza This looks good. Can you review it, please?

2024-07-10 10:25 UTC, merged