contrib/99designs/gqlgen: additional options to reduce noise
DataDog/dd-trace-go pull request #2695
Opened 2024-05-15 04:08 UTC by samsullivan

### What does this PR do?

Adds two new configuration options to `contrib/99designs/gqlgen`, which have a similar end goal of reducing noise:
- `WithSkipFieldsForIntrospectionQuery`
  - if the `OperationName` is `IntrospectionQuery`, spans are not created for each field
- `WithSkipFieldsWithTrivialResolver`
  - if the field resolver is trivial (doesn't require a function / can be accessed directly from the parent object), spans are not created 

### Motivation

We started using `contrib/99designs/gqlgen` middleware recently and noticed it creates way more spans than we intended, most of which have little value for our needs.

Fixes #2684. Fixes #2610.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
  - TODO; see https://github.com/DataDog/dd-trace-go/issues/2684#issuecomment-2111319533... 
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

Unsure? Have a question? Request a review!

2024-05-15 04:21 UTC, samsullivan commented on contrib/99designs/gqlgen/tracer.go
> +		Trivial:   isTrivial,
> TODO: Is this accurate?

Seems like it to me:
- https://graphql.org/learn/execution/#trivial-resolvers
- https://github.com/99designs/gqlgen/blob/master/graphql/context_field.go#L29-L32

2024-05-20 13:40 UTC, samsullivan commented
Alternate naming: `WithOmitTrivialFields` and `WithOmitIntrospectionQuery` :shrug:

2024-05-27 15:59 UTC, seh commented
> Alternate naming: `WithOmitTrivialFields` and `WithOmitIntrospectionQuery` 🤷

How about `WithTrivialFieldsOmitted` and `WithIntrospectionQueriesOmitted`?

What else remains to settle in order to merge this patch?

2024-05-27 18:08 UTC, samsullivan commented
> > Alternate naming: `WithOmitTrivialFields` and `WithOmitIntrospectionQuery` 🤷
> 
> How about `WithTrivialFieldsOmitted` and `WithIntrospectionQueriesOmitted`?

Can push tomorrow.

> What else remains to settle in order to merge this patch?

Nothing but review, as far as I'm aware.

2024-05-28 13:38 UTC, darccio approved these changes

2024-05-28 13:39 UTC, samsullivan commented
@darccio I was just signing on for the day; did you have any opinion on the naming?

2024-06-26 13:38 UTC, rarguelloF requested changes
Overall LGTM! Just a small change to keep the existing options naming convention.

2024-06-26 13:38 UTC, rarguelloF commented on contrib/99designs/gqlgen/option.go
> +
```suggestion
// WithoutTraceInstrospectionQuery skips creating spans for fields when the operation name is IntrospectionQuery.
func WithoutTraceInstrospectionQuery() Option {
	return func(cfg *config) {
		cfg.traceIntrospectionQuery = false
	}
}

// WithoutTraceTrivialResolvedFields skips creating spans for fields that have a trivial resolver.
// For example, a field resolved from an object w/o requiring a custom method is considered trivial.
func WithoutTraceTrivialResolvedFields() Option {
	return func(cfg *config) {
		cfg.traceTrivialResolvedFields = false
	}
}

```

I think its important to keep the existing naming convention, as it has some benefits like making easier to find all the available options from the IDE.

Also, the `skip bool` parameter shouldn't be necessary as its implicit from the `Without`.

2024-06-26 13:45 UTC, samsullivan commented
Thanks for the review @rarguelloF; should be good to go now :+1:

2024-06-27 09:19 UTC, rarguelloF approved these changes

2024-06-27 10:16 UTC, merged

2024-06-30 03:35 UTC, samsullivan commented
Thanks!