contrib/gorm.io/gorm.v1: propagate parent span
DataDog/dd-trace-go pull request #2759
Opened 2024-06-25 13:57 UTC by System-Glitch

### What does this PR do?

- Add a way to use the gorm tracing as a gorm plugin instead of only having the `Open()` option. 
- Start span in before callback instead of after to allow child context to be given to underlying DB driver
- Fix row and raw callbacks not being ordered correctly
- Don't generate spans for `DryRun` statements (e.g. when using a statement or subquery as var)
- Improved tests for the gorm integration

fixes #849 

### Motivation

We are using this plugin as well as the postgres one together and were observing incorrect or confusing spans.

### Reviewer's Checklist

- [x] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

2024-07-03 14:40 UTC, darccio approved these changes
LGTM

2024-07-04 11:49 UTC, rarguelloF requested changes
Thanks for the improvements and the fix 🎉 
I've requested some minor changes. Feel free to skip the test refactor, I can do that myself in a follow-up PR.

2024-07-04 11:49 UTC, rarguelloF commented on contrib/gorm.io/gorm.v1/example_test.go
> +func ExamplePlugin() {
```suggestion
// ExampleNewTracePlugin illustrates how to trace gorm using the gorm.Plugin api. 
func ExampleNewTracePlugin() {
```

(so the example shows up with the `NewTracePlugin` documentation)

2024-07-04 11:49 UTC, rarguelloF commented on contrib/gorm.io/gorm.v1/gorm_test.go
> +		}
```suggestion
		spans := mt.FinishedSpans()
		require.Len(t, spans, 5)
		
		{
			parentSpan := spans[4]
			gormSpan := spans[3]
			pgx1 := spans[2]
			pgx2 := spans[1]
			pgx3 := spans[0]

			assert.Equal(t, "gorm.create", gormSpan.OperationName())
			assert.Equal(t, ext.SpanTypeSQL, gormSpan.Tag(ext.SpanType))
			assert.Equal(t, queryText, gormSpan.Tag(ext.ResourceName))
			assert.Equal(t, "gorm.io/gorm.v1", gormSpan.Tag(ext.Component))

			assert.Equal(t, gormSpan.ParentID(), parentSpan.SpanID())
			assert.Equal(t, pgx1.ParentID(), gormSpan.SpanID())
			assert.Equal(t, pgx2.ParentID(), gormSpan.SpanID())
			assert.Equal(t, pgx3.ParentID(), gormSpan.SpanID())
		}
```

I think I would prefer the test to be a little bit "dumber". Now that the `mocktracer.Start()` lines are added to each specific subtest, we can assert a concrete number of spans, and the expected behavior is more explicit.

(feel free to ignore this refactor if you prefer so, I can do it myself in a subsequent PR)

2024-07-04 13:59 UTC, rarguelloF approved these changes

2024-07-04 14:31 UTC, merged