internal/telemetry: revamp
DataDog/dd-trace-go pull request #2996
Opened 2024-11-27 15:21 UTC by eliottness

### What does this PR do?

This PR rebuilds fron scratch the current instrumentation telemetry client. More informations here:
https://docs.google.com/document/d/1C3xoTZHQZNQ-Jr1w5mMThIkpHNW_4qKRf-J5CNi7G-k/edit?pli=1&tab=t.0#heading=h.88xvn2cvs9dt

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

Unsure? Have a question? Request a review!

2025-02-04 12:16 UTC, RomainMuller requested changes

2025-02-04 12:16 UTC, RomainMuller commented on internal/newtelemetry/metrics.go
> +	}
Sad to join earlier only to split again now...

2025-02-04 12:16 UTC, RomainMuller commented on internal/newtelemetry/metrics.go
> +	}
There are multiple operations involved here... which creates an opportunity for a `Submit`/`Flush` race condition, isn't it?

- `newSubmit = true` enables the data point to be flushed
- `submitTime = now` may or may not be visible by a concurrent flush
- `value = oldValue + newValue` may or may not be visible by a concurrent flush

2025-02-04 12:16 UTC, RomainMuller commented on internal/newtelemetry/telemetrytest/record.go
> +	key := MetricKey{Namespace: namespace, Name: name, Tags: strings.Join(tags, ","), Kind: kind}
There as well, tags are un-sorted, so key is not canonical

2025-02-04 12:16 UTC, RomainMuller commented on internal/newtelemetry/log/log.go
TBH I'd rather have:

```go
func Debug(msg string, opts...LogOption)
func Debugf(format string, argsAndOpts...any)
func Warn(msg string, opts...LogOption)
func Warnf(format string, argsAndOpts...any)
func Error(msg string, opts...LogOption)
func Errorff(format string, argsAndOpts...any)
```

So we don't pass stuff through `fmt.Sprintf` if it was not meant to be (literal `%` etc)

2025-02-04 13:29 UTC, eliottness commented on internal/newtelemetry/api.go
> +	Flush()
Wrong description, fixing this

2025-02-04 13:33 UTC, eliottness commented on internal/newtelemetry/client.go
> +		payloadQueue: internal.NewRingQueue[transport.Payload](config.PayloadQueueSize.Min, config.PayloadQueueSize.Max),
Sadly I added it in the first place because it was not....

2025-02-04 13:37 UTC, eliottness commented on internal/newtelemetry/logger.go
> +type LogOption func(key *loggerKey, value *loggerValue)
That is the only place where I prefered functors because It would probably provide a better stacktrace than with struct literral. And this harmonize well with fmt.Printf variadic args

2025-02-04 16:15 UTC, eliottness commented on internal/newtelemetry/configuration.go
> +		return val
This function is one of the few we can't change the behaviour as we wish because this would compromise the backward compatibility or our searches in the telemetry database backend side (and I know the cases your are talking about are covered and are supposed to go throught the default path with is fmt.Printf

2025-02-04 16:17 UTC, eliottness commented on internal/newtelemetry/distributions.go
> +		if payload := handle.payload(); payload.Metric != "" {
in case payload is the zero value

2025-02-04 16:22 UTC, eliottness commented on internal/newtelemetry/distributions.go
> +	series := make([]transport.DistributionSeries, 0, d.store.Len())
I don't believe the behaviour you are describing is what we want as we are not guaranted that the last value in the range is the last one inserted. Worse case senario is relocation of at most 1KB ONCE over the lifetime of the app. I would bite the bullet on this

2025-02-05 15:07 UTC, eliottness commented on internal/newtelemetry/metrics.go
> +	}
I know but this is the price to use the auto hashing available in go. Anyway this is not in the hot path

2025-02-05 17:06 UTC, eliottness commented on internal/newtelemetry/metrics.go
> +	}
Fixed in https://github.com/DataDog/dd-trace-go/pull/2996/commits/4798807e9f960fe314d59543ba9b0b64e9266ad3

2025-02-05 17:06 UTC, eliottness commented on internal/newtelemetry/metrics.go
> +}
Fixed in https://github.com/DataDog/dd-trace-go/pull/2996/commits/4798807e9f960fe314d59543ba9b0b64e9266ad3

2025-02-05 17:07 UTC, eliottness commented on internal/newtelemetry/telemetrytest/record.go
> +	key := MetricKey{Namespace: namespace, Name: name, Tags: strings.Join(tags, ","), Kind: kind}
Fixed in https://github.com/DataDog/dd-trace-go/pull/2996/commits/e849e5ea907a41de03864f69a859d357d83afdf8

2025-02-06 09:35 UTC, eliottness commented on internal/newtelemetry/logger.go
> +	buf := make([]byte, 1<<12)
Would you mind doing what github calls "suggestions" in this kind of case ?

2025-02-06 10:20 UTC, eliottness commented on internal/newtelemetry/internal/knownmetrics/known_metrics.go
> +)
I also believe this would be safe and better to use but this PR is already very overblown and It would take me some time to get to know dave/jennifer a little better. I still very much want to do what you are talking about. It's only a matter of time before it we rework this

2025-02-06 10:21 UTC, eliottness commented on internal/newtelemetry/internal/knownmetrics/known_metrics.go
> +	return slices.Contains(commonMetrics, decl) || slices.Contains(golangMetrics, decl)
Benchmarks says it's negligable because I only call this once every flush and on the first metric submit in the app lifetime

2025-02-06 10:22 UTC, eliottness commented on internal/newtelemetry/internal/mapper/default.go
> +			}
Yes it is, fortunately the extended heartbeat is not really used much backend-side lol

2025-02-06 10:24 UTC, eliottness commented on internal/newtelemetry/internal/mapper/default.go
> +	if t.extendedHeartbeatRL.Allow() {
This is intended: once a day the extended hearbeat is supposed to replace the normal heartbeat. I can add a comment yes

2025-02-06 10:26 UTC, eliottness commented on internal/newtelemetry/internal/mapper/mapper.go
> +}
Definitively, a very simple one with 3 state, default -> start -> default -> stop -> default

2025-02-06 10:30 UTC, eliottness commented on internal/newtelemetry/internal/mapper/wrapper.go
> +}
Removed this file

2025-02-06 10:33 UTC, eliottness commented on internal/newtelemetry/internal/recorder.go
> +	}
In some swappable metric handles I use the zero value of the recorder struct to look like an empty one

2025-02-06 10:51 UTC, eliottness commented on internal/newtelemetry/internal/ringbuffer.go
> +	pool          sync.Pool
Reworked this for multiple queues to share the same pool

2025-02-06 13:38 UTC, eliottness commented on internal/newtelemetry/client.go
> +}
This was added for retrocompatibilty because it's pretty much used everywhere

2025-02-06 13:41 UTC, eliottness commented on internal/newtelemetry/client.go
> +	}
I am still willing to keep this to simplify some tests since this is not in the hot path

2025-02-06 13:44 UTC, eliottness commented on internal/newtelemetry/client.go
> +	}
I removed this part because it makes no sense: all case where the queue would fill up are because the agent is not responding. The only case where increasing speed is useful is when we send payloads that are too big.

2025-02-06 13:54 UTC, eliottness commented on internal/newtelemetry/client.go
> +			c.payloadQueue.Enqueue(payloads[i:]...)
The thing is that we don't have a lot of documentation on how the endpoints are responding: https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/SchemaDocumentation/Endpoints/trace-agent-intake.md#responses

I added a case about 413 but we may also have cases where the endpoint or the agent proxy is misbehaving that we can't really predict

2025-02-06 13:57 UTC, eliottness commented on internal/newtelemetry/client.go
> +}
Higher level functions in globalclient.go all all Flush() before calling Close() :+1:

2025-02-06 14:30 UTC, eliottness commented on internal/newtelemetry/client_config.go
> +	}
Creating a function that return no dependency should be enough here no ?

2025-02-06 14:31 UTC, eliottness commented on internal/newtelemetry/client_config.go
> +	}
Yes indeed. This okay I believe

2025-02-06 14:32 UTC, eliottness commented on internal/newtelemetry/client_config.go
> +	}
Actually it is,so I made this variable private

2025-02-06 14:33 UTC, eliottness commented on internal/newtelemetry/client_config.go
> +}
Fixed indexToEndpoint :+1:

2025-02-06 21:50 UTC, mtoffl01 commented on internal/newtelemetry/client.go
> +	// flushMapper is the transformer to use for the next flush on the gathered bodies on this tick
Is there a way to make this definition clearer? I don't know if bodies is a typo or has some dual meaning

2025-02-07 09:33 UTC, eliottness commented on internal/globalconfig/globalconfig.go
> +func InstrumentationInstallID() string {
This was just a attempt to create something usable by everyone since I don't believe I have an easy access to those values

2025-02-07 09:38 UTC, eliottness commented on internal/newtelemetry/client.go
> +	// flushMapper is the transformer to use for the next flush on the gathered bodies on this tick
I meant to write "payload" instead of "bodies"

2025-02-10 16:14 UTC, RomainMuller commented on internal/newtelemetry/client_config.go
> +	}
Yes but it should be documented, still :)

2025-02-10 16:16 UTC, RomainMuller commented on internal/newtelemetry/distributions.go
> +		if payload := handle.payload(); payload.Metric != "" {
I guess this is not answering my question... I'm unsure how a zero-value would have ended up in the store?

2025-02-10 16:18 UTC, RomainMuller commented on internal/newtelemetry/internal/knownmetrics/known_metrics.go
> +)
You don't need `dave/jennifer` for this, a simple `text/template` does the job :)

2025-02-10 16:35 UTC, RomainMuller approved these changes

2025-02-10 16:35 UTC, RomainMuller commented on internal/newtelemetry/client.go
> +			}
We _could_ drop any payload for which we receive an HTTP 4XX response (logging that).
It might also be useful to specify what kind of payload is getting dropped so it's easier to track down when that happens.

2025-02-10 16:35 UTC, RomainMuller commented on internal/newtelemetry/client_config.go
> +	DependencyLoader func() (*debug.BuildInfo, bool)
Here you say "if nil, the lib won't sand app-dependencies-loaded"; but then if it's `nil` the initialization sets it to `debug.ReadBuildInfo` (unless `DD_TELEMETRY_DEPENDENCY_COLLECTION_ENABLED` is explicitly set to false-y)... So the documentation lies or at the very least is misleading.

2025-02-10 17:09 UTC, eliottness commented on internal/newtelemetry/client_config.go
> +	DependencyLoader func() (*debug.BuildInfo, bool)
fixed this

2025-02-10 17:10 UTC, eliottness commented on internal/newtelemetry/internal/knownmetrics/known_metrics.go
> +)
In another PR please :(

2025-02-10 17:13 UTC, eliottness commented on internal/newtelemetry/distributions.go
> +		if payload := handle.payload(); payload.Metric != "" {
> I'm unsure how a zero-value would have ended up in the store?
It's not in the store, it's generated by `handle.payload()` which needs a way to transmit upwards the idea that no new data was sent to this metric so there is no need to do a payload about it

2025-02-10 17:17 UTC, eliottness commented on internal/newtelemetry/globalclient.go
> +}
Both new handles would come from the same map so it should be okay

2025-02-17 17:08 UTC, felixge reviewed
Not done with my review yet, but leaving some early comments. Scheduled more time for discussion tomorrow.

2025-02-18 11:06 UTC, eliottness commented on internal/newtelemetry/internal/ringbuffer.go
> +		return rq.IsFull()
You are totally right. Fixed this in https://github.com/DataDog/dd-trace-go/pull/2996/commits/623efa308a410d299305f3b3c1b04a684e8bbbe0

2025-02-18 11:16 UTC, eliottness commented on internal/newtelemetry/internal/ringbuffer.go
> +	head, tail, count int
Funnily enough, my first implementation of this was making the same assumption as you and I specifically added the count for the type of test your `checkCount` function is failing on. As you can see your check is failing in the `distribution-overflow` test that fills up the buffer at max capacity. This a case that should not be reached in a endlessly growing data structure , hence your assumption and mine, but since we have to overflow and overwrite data we have to have this count variable to know if the buffer is full or empty. In your test `(tail - head + len(buffer)) % len(buffer)` returns zero because `head` is equal to `tail` but count is `256` because we actually filled the whole buffer and `tail` looped over. Which means that in this case we cannot differenciate an empty queue and a filled queue without the `count`. I am sure there are other solutions to this issue, hopefully we can discuss this in the next meeting.

2025-02-18 16:50 UTC, eliottness commented on internal/newtelemetry/api.go
> +// - Dependencies: Sending all the dependencies of the application to the backend (for SCA purposes for example)
Fixed this in https://github.com/DataDog/dd-trace-go/pull/2996/commits/78bdf2746cf21ebaab772ad2d24997a3e6f76fcc

2025-02-19 09:36 UTC, felixge approved these changes
Thank you for implementing this and for the effort invested into minimizing the overhead of the solution. This is really good work 🙇 .

That being said, this is a rather complex implementation, and I wasn't able to review every detail due to time constraints, nor would I necessarily be able to catch all issues.

So let's continue with trial by fire and test this in staging.

Additionally let's make sure we have a documented plan to mitigate any customer issues that might come up. I.e. do we have a knob (env var) to turn this off easily?

2025-02-19 10:13 UTC, eliottness commented
> Additionally let's make sure we have a documented plan to mitigate any customer issues that might come up. I.e. do we have a knob (env var) to turn this off easily?

@felixge Agreed. We have a few env vars documented [here](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/cf17b41a30fbf31d54e2cfbfc983875d58b02fe1/GeneratedDocumentation/ApiDocs/v2/development.md#telemetry-environment-variables). The one you are looking for is `DD_INSTRUMENTATION_TELEMETRY_ENABLED`

2025-02-19 11:32 UTC, merged