fix(ddtrace/tracer): avoid tests to fail with error "non-constant format string" from upcoming Go 1.24 release
DataDog/dd-trace-go pull request #3002
Opened 2024-12-02 16:31 UTC by darccio

### What does this PR do?

Upcoming Go 1.24 release introduces a new `go vet` check for printf calls with non-const format and no args. This causes `go test` to fail to run in `gotip`:

```
❯ gotip test gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
# gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
# [gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer]
ddtrace/tracer/abandonedspans.go:276:11: non-constant format string in call to gopkg.in/DataDog/dd-trace-go.v1/internal/log.Warn
ddtrace/tracer/otel_dd_mappings.go:101:14: non-constant format string in call to gopkg.in/DataDog/dd-trace-go.v1/internal/log.Warn
ddtrace/tracer/slog.go:44:13: non-constant format string in call to gopkg.in/DataDog/dd-trace-go.v1/internal/log.Debug
ddtrace/tracer/slog.go:46:12: non-constant format string in call to gopkg.in/DataDog/dd-trace-go.v1/internal/log.Info
ddtrace/tracer/slog.go:48:12: non-constant format string in call to gopkg.in/DataDog/dd-trace-go.v1/internal/log.Warn
ddtrace/tracer/slog.go:50:13: non-constant format string in call to gopkg.in/DataDog/dd-trace-go.v1/internal/log.Error
ddtrace/tracer/option_test.go:341:13: non-constant format string in call to (*testing.common).Fatalf
FAIL    gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer [build failed]
FAIL
```

### Motivation

Avoid unintended consequences from upcoming Go 1.24 release.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

Unsure? Have a question? Request a review!

2024-12-06 21:38 UTC, hannahkm requested changes
Could we check for the same issues in other directories (other than `ddtrace/tracer`)? Running `gotip`  locally gives similar failures in our `ddtrace/opentelemetry` and `internal/appsec`, for example.

2024-12-09 11:26 UTC, darccio commented
@hannahkm I think we'll have to apply a different approach, because our `Error` function kind of expects that the first string argument is usually constant:

![image](https://github.com/user-attachments/assets/50143002-f04a-4c03-93a4-763b26f0d451)

2024-12-09 13:54 UTC, hannahkm approved these changes

2024-12-18 08:46 UTC, eliottness approved these changes

2024-12-18 10:20 UTC, closed without merging