internal/telemetry: remove "testing" import from `internal/telemetry/utils.go`
DataDog/dd-trace-go pull request #3017
Opened 2024-12-07 14:34 UTC by paulcacheux

### What does this PR do?

Currently when you import `dd-trace-go`, you end up having the "testing" std package in your final binary. Not amazing.
This PR fixes this issue by removing the problematic import in `internal/telemetry/utils.go`, and replacing the usage with an interface.

If you have a better idea for `Errorfer` I'm definitely open to it.

I believe this would be fine if it was in a public API, but this is in an internal package so this change should be fine regarding exported API changes.

### Motivation

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

Unsure? Have a question? Request a review!

2024-12-08 14:17 UTC, Julio-Guerra requested changes
Oops indeed :-/ We badly need this script to show the go.mod diff to highlight those unwanted changes...

I suggest moving this function into utils_test.go instead 🙏

2024-12-09 08:39 UTC, eliottness commented
@paulcacheux How about moving this function to the `internal/telemetry/telemetrytest` package ?

2024-12-09 08:42 UTC, paulcacheux commented
@eliottness I'm not sure this would be possible because of the `Configuration` parameter that is defined in `internal/telemetry`. this would create a dependency cycle between `internal/telemetry` and `internal/telemetry/telemetrytest`

2024-12-09 09:01 UTC, Julio-Guerra approved these changes

2024-12-09 09:10 UTC, darccio approved these changes
LGTM

2024-12-09 09:23 UTC, paulcacheux commented
/merge

2024-12-09 10:02 UTC, paulcacheux commented
@darccio @Julio-Guerra please feel free to merge this, I don't have the rights to do so. Thanks !

2024-12-09 10:04 UTC, merged