Allow goroutines not launched by the tracer to stop on tracer.Stop()
DataDog/dd-trace-go pull request #3025
Opened 2024-12-10 21:47 UTC by mtoffl01

### What does this PR do?

Introduces a new package, `contribroutines`, which contains a `stop` channel and an API for getting the channel and closing the channel.
The contribs should get the channel to use as a stop condition for any goroutines they launch, and the tracer should be the only one to stop the channel.

### Motivation
We needed a way for the tracer to stop any goroutines that it does not directly manage on tracer.Stop(); without this mechanism, we were dealing with runaway goroutines.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

Unsure? Have a question? Request a review!

2025-01-17 10:01 UTC, darccio requested changes
LGTM. I left some small nits.

2025-01-17 10:01 UTC, darccio commented on internal/contribroutines/contribroutines.go
> +func InitStopChan() {
```suggestion
func Init() {
```

Just in case this package evolves and needs to initialize more things beyond the stop chan.

2025-01-17 10:01 UTC, darccio approved these changes

2025-01-24 16:51 UTC, darccio approved these changes

2025-01-27 14:06 UTC, kakkoyun reviewed
Looking good 👍 I have a question though.

2025-01-27 14:06 UTC, kakkoyun commented on contrib/database/sql/sql.go
> +	close(t.dbClose)
Could we guarantee that `tracedConnector.Close()` gets called only once? If so, this looks good to me.

However, we could also built some guardrails just in case if it gets called multiple time.

2025-01-27 14:12 UTC, kakkoyun commented on contrib/database/sql/sql.go
> +	close(t.dbClose)
nvm, I got my answer https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/database/sql/sql.go;l=919-923;drc=6de5a7180cc6459235895c76c792a7f15be5625d;bpv=1

It might be a good idea to add comment above the channel close that we only expect it would called once by the `DB.Close()`

2025-01-27 14:13 UTC, kakkoyun approved these changes

2025-01-28 08:45 UTC, kakkoyun approved these changes

2025-02-03 16:09 UTC, merged

2025-02-03 16:12 UTC, rarguelloF commented on contrib/database/sql/sql.go
> +func (t *tracedConnector) Close() error {
This makes me realize we probably had a bug before, since this wraps the original `driver.Connector`, if the original one implemented `Close() error`, our traced version didn't (until this PR).

Maybe we should internally call the original connector `Close` method, in case it implements `io.Closer`?

(btw this is ok to do outside of this PR, since this issue has been there before).