contrib/gofiber/fiber.v2: use UserContext in Middleware for span creation
DataDog/dd-trace-go pull request #3035
Opened 2024-12-12 19:57 UTC by tonyduburque

### What does this PR do?

The Middleware was incorrectly using `c.Context()` instead of `c.UserContext()` to start spans. This could break the propagation of the context defined by other middlewares earlier in the chain.

### Motivation

This change ensures that `tracer.StartSpanFromContext` uses the correct context provided by Fiber, preserving context propagation and ensuring proper tracing behavior.

Fixes #2199

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

2024-12-18 10:17 UTC, darccio approved these changes

2025-01-13 15:19 UTC, rarguelloF requested changes

2025-01-13 15:19 UTC, rarguelloF commented on contrib/gofiber/fiber.v2/fiber.go
> -		span, ctx := tracer.StartSpanFromContext(c.Context(), cfg.spanName, opts...)
could you please write a test reproducing the issue? 🙏

2025-01-14 13:00 UTC, tonyduburque commented on contrib/gofiber/fiber.v2/fiber.go
> -		span, ctx := tracer.StartSpanFromContext(c.Context(), cfg.spanName, opts...)
There is an exemple in the linked issue.
But here is a simpler example :
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"golang.org/x/net/context"
	fibertrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/gofiber/fiber.v2"
)

func initUserContext() fiber.Handler {
	return func(c *fiber.Ctx) error {
		ctx := context.WithValue(c.UserContext(), "key", "value")
		c.SetUserContext(ctx)

		return c.Next()
	}
}

func checkUserContext() fiber.Handler {
	return func(c *fiber.Ctx) error {
		_, ok := c.UserContext().Value("key").(string)
		if !ok {
			return fiber.ErrInternalServerError
		}

		return c.Next()
	}
}

func defaultHandler(c *fiber.Ctx) error {
	return c.SendStatus(fiber.StatusOK)
}

func main() {
	app := fiber.New()

	app.Use(initUserContext())       // Init UserContext with some key value
	app.Use(fibertrace.Middleware()) // Add Datadog middleware
	app.Use(checkUserContext())      // Check if UserContext is correctly set

	app.Get("/", defaultHandler)

	if err := app.Listen(":3000"); err != nil {
		panic(err)
	}
}
```

The expected outcome is a response with a status code of 200, but instead, a response with a status code of 500 is returned.

If the fibertrace middleware is removed, a response with a status code of 200 is obtained as expected.

2025-01-15 10:44 UTC, tonyduburque commented on contrib/gofiber/fiber.v2/fiber.go
> -		span, ctx := tracer.StartSpanFromContext(c.Context(), cfg.spanName, opts...)
I modified the UserContext test to include the necessary checks

2025-01-20 15:14 UTC, rarguelloF approved these changes
LGTM, thanks for fix and writing the test! @tonyduburque

2025-01-20 15:20 UTC, merged