output supported versions
DataDog/dd-trace-go pull request #3058
Opened 2024-12-24 15:32 UTC by quinna-h

### What does this PR do?

### Motivation

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

Unsure? Have a question? Request a review!

2024-12-27 00:03 UTC, quinna-h commented on .github/workflows/apps/output_integration_versions.go
> +	instrumentedSet := map[string]struct{}{
This is from https://github.com/DataDog/orchestrion?tab=readme-ov-file#supported-libraries

2025-01-02 15:20 UTC, quinna-h commented on integration_go.mod
> -	github.com/google/pprof v0.0.0-20230817174616-7a8ec2ada47b
Probably put these changes in a separate PR

2025-01-03 12:36 UTC, rarguelloF requested changes
The generated format looks good! I pointed out some problems / wrong info I see in the outputted markdown.

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/go-redis/redis/v9 | v9.7.0   // renamed to redis/go-redis in v9 | v9.7.0 | false
```suggestion
| github.com/redis/go-redis/v9 | v9.7.0 | v9.7.0 | false
```

First column should be the module name (not the repo name) + those comments shouldn't be here IMO

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/globalsign/mgo | v0.0.0-20181015135952-eeefdecb41b8 | github.com/globalsign/mgo | false
third column doesn't contain a version

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/denisenkom/go-mssqldb | v0.11.0 | v0.12.3 | false
this is not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/bradfitz/gomemcache | v0.0.0-20230611145640-acc696258285 | github.com/bradfitz/gomemcache | false
third column does not contain a version

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/aws/aws-sdk-go-v2/service/sqs | v1.24.4 | v1.37.3 | false
```suggestion
```

IMHO all these shouldn't show up here as they can be confusing for users reading it, as they don't map to a specific integration (the integration is just `github.com/aws/aws-sdk-go-v2`).

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/aws/aws-sdk-go | v1.44.327 | v1.55.5 | false
```suggestion
| github.com/aws/aws-sdk-go | v1.44.327 | v1.55.5 | true
```

this one is auto-instrumented: https://github.com/DataDog/orchestrion/blob/main/internal/injector/builtin/yaml/cloud/aws-sdk.yml

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/go-sql-driver/mysql | v1.6.0 | v1.8.1 | false
not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/google/uuid | v1.5.0 | v1.6.0 | false
not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/graphql-go/handler | v0.2.3 | v0.2.4 | false
```suggestion
```

this one can be removed (not an integration)

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/hashicorp/go-multierror | v1.1.1 | v1.1.1 | false
not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/hashicorp/vault/sdk | v0.9.2 | v0.14.0 | false
it is auto-instrumented: https://github.com/DataDog/orchestrion/blob/f729796890d3aa12a391e9eb39120a709ae13bcc/internal/injector/builtin/yaml/api/vault.yml#L8

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/microsoft/go-mssqldb | v0.21.0 | v1.8.0 | false
```suggestion
```

not integrations

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/uptrace/bun/dialect/sqlitedialect | v1.1.17 | v1.2.6 | false
```suggestion
```

not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| github.com/vektah/gqlparser/v2 | v2.5.16 | v2.5.21 | false
```suggestion
```

not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp | v0.44.0 | v0.58.0 | false
```suggestion
```

not an integration

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| gorm.io/driver/sqlserver | v1.4.2 | v1.5.4 | false
```suggestion
```

not integrations

2025-01-03 12:36 UTC, rarguelloF commented on supported_versions.md
> +| google.golang.org/protobuf | v1.33.0 | v1.36.1 | false
```suggestion
```

not an integration

2025-01-03 12:36 UTC, rarguelloF commented on integration_go.mod
>  	github.com/jackc/pgx/v5 v5.6.0
How is this go.mod being generated?

2025-01-03 15:37 UTC, quinna-h commented on supported_versions.md
> +| github.com/denisenkom/go-mssqldb | v0.11.0 | v0.12.3 | false
marking the subsequent comments as resolved, addressed these in #3064

2025-01-06 16:06 UTC, quinna-h commented on supported_versions.md
> +| github.com/aws/aws-sdk-go-v2 | v1.20.3 | v2.0.0-preview.4+incompatible | true
these are removed in #3064

2025-03-10 16:25 UTC, darccio commented
@quinna-h As part of our upcomding release, we are reviewing all in-flight PRs. Please consider closing it or rebasing to `v2-dev` if you want to merge it for the next release after `v2.0.0`.

2025-03-10 17:26 UTC, quinna-h commented
Replaced by #3070

2025-03-10 17:26 UTC, closed without merging