fix(ddtrace/tracer): fix panic in SQLCommentCarrier
DataDog/dd-trace-go pull request #3062
Opened 2024-12-30 12:13 UTC by rarguelloF

### What does this PR do?

Fixes https://github.com/DataDog/dd-trace-go/issues/2837

### Motivation

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.
- [ ] For internal contributors, a matching PR should be created to the `v2-dev` branch and reviewed by @DataDog/apm-go.

Unsure? Have a question? Request a review!

2025-01-07 09:45 UTC, darccio requested changes

2025-01-07 09:45 UTC, darccio commented on ddtrace/tracer/spancontext.go
> +	}
@rarguelloF I wonder if we could fix this by allowing to fail if `c.span` is nil, but checking that the span isn't nil in the code that relies on `meta` in `sqlcomment.go`:

```go
	case DBMPropagationModeService:
		if ctx, ok := spanCtx.(*spanContext); ok && ctx.span != nil {
			if e, ok := ctx.meta(ext.Environment); ok && e != "" {
				tags[sqlCommentEnv] = e
			}
```

My rationale is that introducing this check here may yield to hidden behaviour. Also, to me this seems an example of not enough coverage, as it only impact a single case of DBM propagation.

We should add a test case covering this case, if possible. WDYT?

2025-01-07 09:53 UTC, rarguelloF commented on ddtrace/tracer/spancontext.go
> +	}
> introducing this check here may yield to hidden behaviour.

I don't think any caller of a non-nil `*spanContext` of `.meta()` should be expecting a panic in general + the only callers of this function are in this `sqlcomment.go` file.

Making this check would make things a little bit more redundant (we would have to check this in N places where this method is called) and expects the caller to know these internal implementation details (the caller needs to know that a non-nil `*spanContext` might have a nil `span` - which btw is a private field), which IMHO is not a good thing...

2025-01-07 14:05 UTC, darccio commented on ddtrace/tracer/spancontext.go
> +	}
> I don't think any caller of a non-nil *spanContext of .meta() should be expecting a panic in general + the only callers of this function are in this sqlcomment.go file.

That's why I suggested doing this the other way around. We are adding code that has general impact for somethingt that only happens in a corner case of a module in the whole tracer 😄 Also, doesn't seem strange that only impacts this module but not the rest?

These are internal APIs, so I'm fine having extra requirements.

2025-01-07 14:05 UTC, darccio commented on ddtrace/tracer/spancontext.go
> +	}
> Agree! Isn't the new test case that I added enough? or were you thinking on something else/different?

I had in mind to actually test the switch branch that panics when you run `Inject` on a recently extracted context.

2025-01-09 12:42 UTC, rarguelloF commented on ddtrace/tracer/spancontext.go
> +	}
As discussed in private:
- Will move the nil check to the callers instead.
- Remove the `spanContext.meta` method to `getMeta` function

2025-01-09 12:55 UTC, darccio approved these changes

2025-01-10 15:17 UTC, merged