contrib/go-redis/redis.v8: support go-redis.v8
DataDog/dd-trace-go pull request #727
Opened 2020-09-09 14:20 UTC by sfroment

This is simply a port of contrib/go-redis/redis, but for go-redis.v8 with the new Hook mechanism.

2020-09-16 17:15 UTC, knusbaum requested changes
Thanks for this. I only have a few comments.

2020-09-23 09:16 UTC, sfroment commented
Sorry for the delay updated the review, do not hesitate if there is anything else that need to me done :)

2020-09-28 19:51 UTC, knusbaum submitted a review, later dismissed
LGTM. Thank you @sfroment

2020-09-29 05:59 UTC, johejo commented on contrib/go-redis/redis.v8/redis.go
> +}
I think we should check the implementation of the Hook interface at compile time.
```
var _ redis.Hook = (*datadogHook)(nil)
```

2020-09-29 06:03 UTC, johejo commented on contrib/go-redis/redis.v8/redis.go
> +}
Cmder implements fmt.Stringer at v8. https://pkg.go.dev/github.com/go-redis/redis/v8#Cmder
We don't need this hack.

2020-10-01 16:54 UTC, knusbaum requested changes

2020-10-01 16:54 UTC, knusbaum commented on contrib/go-redis/redis.v8/redis.go
> +var _ redis.Hook = (*datadogHook)(nil)
Generally we put these checks in the test files.

2020-10-02 18:36 UTC, knusbaum submitted a review, later dismissed
This looks great. Thanks.

@sfroment Since `v1.27.0` was released, the PR needs to be rebased on `v1` in order to get the tests to pass. 
I am happy to rebase this for you if you don't have time.

2020-10-05 15:48 UTC, knusbaum approved these changes

2020-10-05 15:49 UTC, merged