ddtrace/tracer: StartSpanFromContext should work nil ctx on Go 1.15
DataDog/dd-trace-go pull request #749
Opened 2020-09-30 18:21 UTC by evanj

Previously, StartSpanFromContext would "work" with nil ctx. Using the
ctx (e.g. ctx.Value) would later cause a segfault. With Go 1.15,
calling StartSpanFromContext now panics. Preserve the existing
behaviour by defaulting to context.Background(). Document this
behaviour. Add a test.

Without the fix, on Go 1.14 this new test panics with "runtime error:
invalid memory address or nil pointer dereference" when calling
context.Value. On Go 1.15 it fails with "cannot create context from
nil parent" when calling StartSpanFromContext.

2020-09-30 18:41 UTC, knusbaum requested changes
👍 
Generally we shouldn't detect and correct `nil` contexts, since [passing nil contexts is invalid](https://godoc.org/context), rather fixing it in the caller.

However, on the API boundary I think it's a good idea. Plus, other existing functions already check for and accept `nil` contexts, like `SpanFromContext`.

2020-09-30 18:41 UTC, knusbaum commented on ddtrace/tracer/context_test.go
> +	// Go == 1.15: StartSpanFromContext(nil, ...) would panic: cannot create context from nil parent
We can leave these comments out. This commit fixes the panic, so explaining in the comment is unnecessary.

2020-09-30 18:52 UTC, knusbaum submitted a review, later dismissed
LGTM. Thanks.

2020-10-01 06:34 UTC, gbbr requested changes

2020-10-01 06:34 UTC, gbbr commented on ddtrace/tracer/context.go
> +	// default to context.Background() to avoid panics on Go >= 1.15
Can you please move this comment inside the `if` statement?

2020-10-01 06:34 UTC, gbbr commented on ddtrace/tracer/context.go
> +
And remove this empty line please.

2020-10-01 15:01 UTC, evanj commented
I have made the suggested changes; thanks!

2020-10-01 23:26 UTC, knusbaum submitted a review, later dismissed

2020-10-02 06:17 UTC, gbbr reviewed
Thanks for making the changes, and sorry for coming back with yet another request. Can you please apply it and then we're good to merge? 🙏

2020-10-02 06:17 UTC, gbbr commented on ddtrace/tracer/context.go
> +// If ctx is nil, this will use context.Background().
This is nothing but a safety mechanism, I don't think it warrants documentation changes.

2020-10-02 19:32 UTC, knusbaum approved these changes

2020-10-26 09:01 UTC, gbbr approved these changes

2020-11-04 17:52 UTC, merged