all: add debug logs to Go tracer/integrations
DataDog/dd-trace-go pull request #816
Opened 2021-01-11 22:30 UTC by nicoledanuwidjaja

Continuation of [this PR](https://github.com/DataDog/dd-trace-go/pull/677) by @knusbaum. Updates debug logs for newer integrations at config startup. 

Open to discussion for now to see if any parts of the issue are unaddressed.

Fixes #653

2021-01-12 21:20 UTC, nicoledanuwidjaja commented
The `go-pg/pg.v10` integration doesn't have a config; should a debug log be added to the database wrapper?

2021-01-13 19:25 UTC, knusbaum commented
@nicoledanuwidjaja I think we should add a line to the function here:
https://github.com/DataDog/dd-trace-go/blob/3ed2a2784fd7adb414f2f47dbb6b6a1d301cdf8c/contrib/go-pg/pg.v10/pg_go.go#L18-L21

2021-01-13 22:23 UTC, knusbaum requested changes
Looks pretty good. Just a couple minor things.

The largest is that we should add a test for the span creation log.

All integration logs should have the full path starting with `contrib/` for consistency. I marked all the ones I saw with comments.

2021-01-13 22:23 UTC, knusbaum commented on ddtrace/tracer/tracer.go
> +	log.Debug("Tracer starting. %#v", c)
I think we can remove this log. We already have startup logging [here](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/tracer.go#L97).

2021-01-13 22:23 UTC, knusbaum commented on contrib/julienschmidt/httprouter/httprouter.go
> +	log.Debug("julienschmidt/httprouter: Configuring Router: %#v", cfg)
Let's add `contrib/` to the path here for consistency.

2021-01-13 22:23 UTC, knusbaum commented on contrib/gopkg.in/jinzhu/gorm.v1/gorm.go
> +	log.Debug("gopkg.in/jinzhu/gorm.v1: Registering Callbacks: %#v", cfg)
Let's add `contrib/` to the path here as well.

2021-01-13 22:23 UTC, knusbaum commented on contrib/gofiber/fiber.v2/fiber.go
> +	log.Debug("gofiber/fiber.v2: Middleware: %#v", cfg)
`contrib/` should be added here.

2021-01-13 22:23 UTC, knusbaum commented on contrib/go-pg/pg.v10/pg_go.go
> +	log.Debug("go-pg/pg.v10: Wrapping Database")
`contrib/` here too.

2021-01-13 22:23 UTC, knusbaum commented on ddtrace/tracer/tracer.go
> +	log.Debug("Started Span: %v, Operation: %s, Resource: %s, Tags: %v, %v", span, span.Name, span.Resource, span.Meta, span.Metrics)
This format is complicated and it isn't clear what exactly the output will be like.
We should add a test to `ddtrace/tracer/log_test.go` that tests this output to ensure the format continues to make sense in the future.

2021-02-09 08:33 UTC, gbbr approved these changes
LGTM

2021-02-09 22:45 UTC, merged

2021-02-10 17:08 UTC, nicoledanuwidjaja commented
@felixge Put up a PR to fix it. Thanks!
https://github.com/DataDog/dd-trace-go/pull/840

2021-02-11 09:40 UTC, felixge commented
Thanks @nicoledanuwidjaja : )