tracer/tracer.go: sample inherited span
DataDog/dd-trace-go pull request #818
Opened 2021-01-17 01:05 UTC by Jesse-Cameron

sample the span via config if the parent span ctx does not contain
the necessary sampling priority details.

fixes: #793

2021-01-28 18:52 UTC, knusbaum requested changes
Thanks for this! 

I think this is close. 

The `StartSpan` logic is a little convoluted. For instance, we don't set the span's context until after [this block](https://github.com/DataDog/dd-trace-go/blob/adb865a21a52f60f10d77ca3e6cf4e2f5b8db4e2/ddtrace/tracer/tracer.go#L269-L288). I think that is because [`newSpanContext` uses `span.SpanID` and `span.TraceID` to populate the context's values.](https://github.com/DataDog/dd-trace-go/blob/adb865a21a52f60f10d77ca3e6cf4e2f5b8db4e2/ddtrace/tracer/spancontext.go#L47-L51) It's a little confusing because in the code block right before we call `newSpanContext`, we set the [span id and trace id from the parent context](https://github.com/DataDog/dd-trace-go/blob/adb865a21a52f60f10d77ca3e6cf4e2f5b8db4e2/ddtrace/tracer/tracer.go#L271-L272) anyway.

> BTW: I had some trouble getting the tests to work in my instance of circleci due to plan limitations. Would appreciate some help running in the datadog instance if possible :)

You are free to push commits to this PR, and CircleCI will run. You are also free to put up a draft PR at any time where tests will run. 

Another option (and the easiest, in my opinion) is to run the tracer tests locally. This is more difficult for `contrib/*`, but since you're working on `ddtrace/tracer`, you should be able to `cd` into the `ddtrace/tracer` directory and run `go test` to run all the core tests.

2021-02-04 02:33 UTC, Jesse-Cameron commented
Hey @knusbaum ,

I will admit, I found the `StartSpan` logic a little confusing myself.

> The StartSpan logic is a little convoluted. For instance, we don't set the span's context until after this block. I think that is because newSpanContext uses span.SpanID and span.TraceID to populate the context's values. It's a little confusing because in the code block right before we call newSpanContext, we set the span id and trace id from the parent context anyway.

I'm not sure that we can set the `samplingPriority` inside of the first `if context != nil` block. I did originally try this. But the `context.samplingPriority()` call requires the context to have a `trace`. And that `trace` to have a `samplingPriority`. Which keep causing the tests to fail.

When why I elected to try and do the sampling after the `newSpanContext`.

> You are free to push commits to this PR, and CircleCI will run. You are also free to put up a draft PR at any time where tests will run.

Weird, when I push to this branch it seems to be running under my plan, not the datadog one. Am I doing something wrong?

2021-02-04 02:55 UTC, Jesse-Cameron commented on ddtrace/tracer/tracer.go
>  		t.sample(span)
Yep, I think I know what you are saying. And I've made that change in 4377471.

2021-02-04 03:02 UTC, Jesse-Cameron commented on ddtrace/tracer/tracer.go
> -		return
Yep, this was left in by mistake. Have removed

2021-02-22 07:30 UTC, Jesse-Cameron commented
Hey @knusbaum , sorry to prod, but have you had a moment to look over this one? 😅

2021-05-26 16:55 UTC, knusbaum approved these changes
@Jesse-Cameron Thanks for your patience. I was out on leave.

I think this is a very clean solution to the issue. Thanks for working on this with us.

2021-05-26 16:58 UTC, knusbaum commented
Figuring out the CircleCI thing. Very strange it's running under your account.

2021-05-27 04:55 UTC, Jesse-Cameron commented
Np @knusbaum , everyone deserves a break!

> Figuring out the CircleCI thing. Very strange it's running under your account.

yeah I found this article: https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

I have unfollowed my fork. Perhaps, we can close this PR and open it again?

2021-05-27 05:03 UTC, Jesse-Cameron commented
Ah okay. That seems to have fixed it. The failing test is due to the tagging:
![image](https://user-images.githubusercontent.com/3723654/119768864-bb661e80-befc-11eb-8499-6b642dddaa7a.png)

2021-06-15 16:46 UTC, knusbaum approved these changes
LGTM

2021-06-15 16:46 UTC, merged