contrib/confluentinc/confluent-kafka-go/kafka: Use kafka headers as c…
DataDog/dd-trace-go pull request #943
Opened 2021-06-02 18:00 UTC by hexa00

…ontext when producing

Before this patch when producing a message, the general producer context was
used when producing messages.

This made it impossible to attach a parent span to a produced message.

With this patch messages headers are checked when producing messages for a span
context and the span is created as a child if a parent span is present.

Also StartSpanFromContext is changed to just StarSpan since using the global
consumer/producer context has no use.

Fixed #941

2021-06-29 13:30 UTC, knusbaum requested changes
Hi, @hexa00 
We should include clear examples of how to use this, as well as tests for the behavior.

We also need to maintain the existing behavior for anyone using the `WithContext` option. IMO, we should mark `WithContext` deprecated.

2021-06-29 13:42 UTC, hexa00 commented
@knusbaum thank you, a few questions: 
 - Where should the examples be ? Would the tests work as examples ?
 - OK to maintain the behavior and mark as deprecated , is a comment with Deprecated:  the proper way ?

2021-06-29 13:48 UTC, knusbaum commented
@hexa00 

Sorry, I should have been clearer. :)

- For examples, we use the [Go example format](https://golang.org/pkg/testing/#hdr-Examples) (see our [sarama examples](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/Shopify/sarama/example_test.go) and [this go blog](https://blog.golang.org/examples))
- Adding a note about deprecation to the function documentation is good enough for deprecating the function.

Thanks.

2021-06-29 14:01 UTC, hexa00 commented
@knusbaum great thanks for the info, I'll work on that today

2021-06-29 19:10 UTC, hexa00 commented
@knusbaum this PR is ready for a second look:

Changes:
  - Example / test for the new behavior
  - Test for the old behavior
  - Deprecated WithContext()
  - Kept the old behavior if a context containing a span is set on the producer
  - Rebased on latest v1

Let me know what you think, thanks! :)

2021-07-08 14:49 UTC, knusbaum requested changes
@hexa00 Looks great. Thanks for making those changes.

Just one more change to the new example file and we should be good.

2021-07-08 14:49 UTC, knusbaum commented on contrib/confluentinc/confluent-kafka-go/kafka/example_test.go
> +package kafka_test
Please add the license header to this file.

2021-07-08 14:54 UTC, hexa00 commented
@knusbaum indeed , fixed and rebased

2021-07-14 01:46 UTC, knusbaum approved these changes
Looks good. 👍

2021-07-14 01:47 UTC, merged