Add default service name to gorm and sql
DataDog/dd-trace-go pull request #970
Opened 2021-07-29 20:57 UTC by afarbos

Use globalconfig to set proper and default service name in gorm and sql contrib

2021-08-05 02:04 UTC, knusbaum commented
Can you explain the reason for this PR? Our current scheme only uses the global service name for http servers

2021-08-18 18:59 UTC, afarbos commented
> Can you explain the reason for this PR? Our current scheme only uses the global service name for http servers.
> 
> You may want to open an issue to discuss changes like this before we look at a PR. Please take a look at the [Contribution Guidelines](https://github.com/DataDog/dd-trace-go/blob/v1/CONTRIBUTING.md) too.

Sorry for the delay, I updated the description to add necessary explanations.
Let me know if I should open an issue instead, I thought the change was simple to visualize.

2021-08-19 07:05 UTC, gbbr requested changes
If you check the documentation for `globalconfig.ServiceName`, you will understand why some integrations don't use it:

https://github.com/DataDog/dd-trace-go/blob/c0f4b736808a09e0716171201f968927c232da5e/internal/globalconfig/globalconfig.go#L45

2021-08-19 21:30 UTC, knusbaum commented
Closing. This seems to be superseded by #982

2021-08-19 21:30 UTC, closed without merging