Trace Enabled Feature
DataDog/dd-trace-go pull request #991
Opened 2021-08-29 13:12 UTC by AHHussain569

* Allow for tracing to be enabled based on an environment variable or start option
* When disabled, tracer is replaced on Start with NoopTracer

resolves #946

2021-08-29 20:04 UTC, AHHussain569 commented
Could someone with permissions please re-run the pipeline, the specific failing tests are unrelated to the code changes made and pass locally

2021-08-30 06:43 UTC, gbbr submitted a review, later dismissed
Please take a moment to read our contribution guidelines...

Lastly, why not do this in your own program?
```go
if ok, err := strconv.ParseBool(os.Getenv("DD_TRACE_ENABLED")); ok && err == nil {
    tracer.Start(...)
    defer tracer.Stop()
}
```

No need to add this into the library.

2021-09-01 15:30 UTC, knusbaum commented
Hey, @gbbr. I approved this change in #946, since this is a feature present in many other tracers and should be a small code change.
Is this OK with you, or do we need to revisit the proposal?

2021-11-11 21:55 UTC, knusbaum commented
I've merged @gbbr's suggestions and this can be merged once the tests pass.

2021-11-11 22:17 UTC, knusbaum requested changes
Wrong variable name. I'm applying some suggestions.

2021-11-11 22:17 UTC, knusbaum commented on ddtrace/tracer/option.go
> +	c.traceEnabled = internal.BoolEnv("DD_TRACE_ENABLED", true)
```suggestion
	c.enabled = internal.BoolEnv("DD_TRACE_ENABLED", true)
```

2021-11-11 22:17 UTC, knusbaum commented on ddtrace/tracer/option.go
> +}
```suggestion
func WithTraceEnabled(enabled bool) StartOption {
	return func(c *config) {
		c.enabled = enabled
	}
}
```

2021-11-11 22:17 UTC, knusbaum commented on ddtrace/tracer/option_test.go
> +			assert.True(t, c.traceEnabled)
```suggestion
			assert.True(t, c.enabled)
```

2021-11-11 22:17 UTC, knusbaum commented on ddtrace/tracer/option_test.go
> +			assert.False(t, c.traceEnabled)
```suggestion
			assert.False(t, c.enabled)
```

2021-11-11 22:17 UTC, knusbaum commented on ddtrace/tracer/option_test.go
> +}
```suggestion
func TestWithTraceEnabled(t *testing.T) {
	t.Run("WithTraceEnabled", func(t *testing.T) {
		assert := assert.New(t)
		c := newConfig(WithTraceEnabled(false))
		assert.False(c.enabled)
	})

	t.Run("env", func(t *testing.T) {
		assert := assert.New(t)
		os.Setenv("DD_TRACE_ENABLED", "false")
		defer os.Unsetenv("DD_TRACE_ENABLED")
		c := newConfig()
		assert.False(c.enabled)
	})

	t.Run("env-override", func(t *testing.T) {
		assert := assert.New(t)
		os.Setenv("DD_TRACE_ENABLED", "false")
		defer os.Unsetenv("DD_TRACE_ENABLED")
		c := newConfig(WithTraceEnabled(true))
		assert.True(c.enabled)
	})
}
```

2021-11-11 22:17 UTC, knusbaum commented on ddtrace/tracer/tracer.go
> +	if !t.config.traceEnabled {
```suggestion
	if !t.config.enabled {
```

2021-11-11 22:33 UTC, knusbaum approved these changes

2021-11-12 15:41 UTC, merged